{
  # Generated by luxnix-render-boot-decryption-config; do not edit directly.
  boot.initrd.availableKernelModules = [
    "dm-crypt"
    "sd_mod"
    "usb_storage"
  ];

  boot.initrd.luks.devices = {
    "cryptroot" = {
      keyFile = "/dev/disk/by-uuid/49a2171e-3ef3-4506-950b-3cc3d76a396e";
      keyFileOffset = 52428800;
      keyFileSize = 4096;
      preLVM = true;
      keyFileTimeout = 10; # If no prompt is displayed, try pressing Esc.
    };
  };
}
