set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: luxnix-render-boot-decryption-config \
  --output <absolute-path> \
  --usb-uuid <uuid> \
  --offset-bytes <positive-integer> \
  --keyfile-size <positive-integer> \
  --luks-device <name> [--luks-device <name> ...]

Render only: this command writes one formatted Nix configuration to --output.
It never formats or mounts devices, creates key material, or changes LUKS keys.
EOF
}

fail() {
  echo "luxnix-render-boot-decryption-config: $*" >&2
  exit 2
}

require_positive_integer() {
  local name="$1"
  local value="$2"

  [[ "$value" =~ ^[1-9][0-9]*$ ]] || fail "$name must be a positive integer"
}

output=""
usb_uuid=""
offset_bytes=""
keyfile_size=""
declare -a luks_devices=()

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --output)
      [[ "$#" -ge 2 ]] || fail "--output requires a value"
      output="$2"
      shift 2
      ;;
    --usb-uuid)
      [[ "$#" -ge 2 ]] || fail "--usb-uuid requires a value"
      usb_uuid="$2"
      shift 2
      ;;
    --offset-bytes)
      [[ "$#" -ge 2 ]] || fail "--offset-bytes requires a value"
      offset_bytes="$2"
      shift 2
      ;;
    --keyfile-size)
      [[ "$#" -ge 2 ]] || fail "--keyfile-size requires a value"
      keyfile_size="$2"
      shift 2
      ;;
    --luks-device)
      [[ "$#" -ge 2 ]] || fail "--luks-device requires a value"
      luks_devices+=("$2")
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[[ "$output" == /* ]] || fail "--output must be an absolute path"
[[ -n "$usb_uuid" ]] || fail "--usb-uuid is required"
[[ "$usb_uuid" =~ ^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$ ]] \
  || fail "--usb-uuid must be a canonical UUID"
require_positive_integer "--offset-bytes" "$offset_bytes"
require_positive_integer "--keyfile-size" "$keyfile_size"
[[ "${#luks_devices[@]}" -gt 0 ]] || fail "at least one --luks-device is required"

for luks_device in "${luks_devices[@]}"; do
  [[ "$luks_device" =~ ^[A-Za-z0-9._-]+$ ]] || fail "--luks-device must be a simple LUKS mapping name"
done

output_directory="$(dirname "$output")"
[[ -d "$output_directory" ]] || fail "the parent directory of --output must already exist"

temporary_output="$(mktemp --suffix=.nix "$output_directory/.boot-decryption-config.XXXXXX")"
cleanup() {
  rm -f "$temporary_output"
}
trap cleanup EXIT

{
  cat <<EOF
{
  # Generated by luxnix-render-boot-decryption-config; do not edit directly.
  boot.initrd.availableKernelModules = [ "dm-crypt" "sd_mod" "usb_storage" ];

  boot.initrd.luks.devices = {
EOF

  for luks_device in "${luks_devices[@]}"; do
    cat <<EOF
    "${luks_device}" = {
      keyFile = "/dev/disk/by-uuid/${usb_uuid}";
      keyFileOffset = ${offset_bytes};
      keyFileSize = ${keyfile_size};
      preLVM = true;
      keyFileTimeout = 10; # If no prompt is displayed, try pressing Esc.
    };
EOF
  done

  cat <<'EOF'
  };
}
EOF
} >"$temporary_output"

nixfmt "$temporary_output"
mv "$temporary_output" "$output"
trap - EXIT
