postgres_host_test_roles:
  postgres.main.enable: "true"
postgres_host_test_luxnix:
  generic-settings.postgres.extraAuthentication: |
    # dev-01
    host  all all 172.16.255.102/32 scram-sha-256
    host  all postgres 172.16.255.102/32 scram-sha-256
    # dev-02
    host  all all 172.16.255.108/32 scram-sha-256
    host  all postgres 172.16.255.108/32 scram-sha-256
