postgres_host_test_roles:
  postgres.main.enable: "true"
postgres_host_test_luxnix:
  generic-settings.postgres.activeAuthentication: |
    #type database DBuser address auth-method optional_ident_map
    local sameuser all peer map=superuser_map
    host  all all ${config.luxnix.generic-settings.adminVpnIp}/32 scram-sha-256
    host  replication ${config.roles.postgres.main.replUser} ${config.luxnix.generic-settings.adminVpnIp}/32 scram-sha-256
    host  ${config.roles.postgres.main.devUser} ${config.roles.postgres.main.devUser} ${config.luxnix.generic-settings.adminVpnIp}/32 scram-sha-256
    host  all postgres ${config.luxnix.generic-settings.adminVpnIp}/32 scram-sha-256
    # dev-01
    host  all all 172.16.255.102/32 scram-sha-256
    host  all postgres 172.16.255.102/32 scram-sha-256
    # dev-02
    host  all all 172.16.255.108/32 scram-sha-256
    host  all postgres 172.16.255.108/32 scram-sha-256

  generic-settings.postgres.activeIdentMap: |
    # ArbitraryMapName systemUser DBUser
    superuser_map      root      postgres
    superuser_map      root      ${config.roles.postgres.main.replUser}
    superuser_map      ${config.user.admin.name}     ${config.user.admin.name}
    superuser_map      ${config.user.admin.name}     postgres
    superuser_map      ${config.user.admin.name}     endoregClient
    superuser_map      postgres  postgres

    # Let other names login as themselves
    superuser_map      /^(.*)$   \1
