# inventory/group_vars/all.yml
---
ansible_groups:
  - "common"
group_roles: {}
group_services: {}
group_luxnix:
  generic_settings.enable: "true"
  vault.enable: "true"
  vault.dir: "'/etc/secrets/vault'"
  vault.key: "'/etc/secrets/.key'"
  vault.psk: "'/etc/secrets/.psk'"

ansible_key_dir: "{{ luxnix_dest }}/secrets/ansible-vault-keys"
ansible_key_source_dir: "{{ luxnix_dev_repo }}/secrets/ansible-vault-keys-source"

lx_vault_dir: "~/.lxv"
lx_vault_key: "~/.lxv/.key"

luxnix_dev_repo: "/home/admin/dev/luxnix"
luxnix_repo: "https://github.com/wg-lux/luxnix.git"
luxnix_dest: "/home/admin/lx-production"
luxnix_branch: "main"
# luxnix_secrets: []

ansible_user: admin
ansible_become_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: "{{ luxnix_dest }}/.devenv/state/venv/bin/python"

local_users_passwords_dir: "{{ luxnix_dest }}/secrets/user-passwords/{{ inventory_hostname }}"
admin_password_file: "{{ local_users_passwords_dir }}/admin_raw"
admin_password_file_source: "{{ luxnix_dev_repo }}/secrets/user-passwords/{{ inventory_hostname }}/admin_raw"

authentication:
  dev_01:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEh2Bg+mSSvA80ALScpb81Q9ZaBFdacdxJZtAfZpwYkK
  dev_02: {} # Add gc-05 pubkey here
  dev_03:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDBJcYjGNIwOUs+KG8TbBxPWtJFEqni0p+1J5Yz++Aos
  agl_admin:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM7vvbgQtzi4GNeugHSuMyEke4MY0bSfoU7cBOnRYU8M

network_conf:
  domain: "endo-reg.net"

aglnet_conf:
  domain: "{{ network_conf.domain }}"
  subnet: "172.16.255.0"
  subnetIntern: "255.255.255.0"
  subnetSuffix: "32"
  caPath: "/etc/openvpn/ca.pem"
  tlsAuthPath: "/etc/openvpn/tls.pem"
  serverCertPath: "/etc/openvpn/crt.crt"
  serverKeyPath: "/etc/openvpn/key.key"
  dhPath: "/etc/openvpn/dh.pem"
  clientConfigDir: "/etc/openvpn/ccd"
  backupNameservers:
    - "8.8.8.8"
    - "1.1.1.1"
