# inventory/group_vars/all.yml
---
secret_dir: "/etc/secrets"
lx_vault_dir: "{{ secret_dir }}/vault"
lx_vault_key: "{{ secret_dir }}/.key"
lx_vault_psk: "{{ secret_dir }}/.psk"
lx_vault_dir_src: "/home/admin/.lxv"
lx_vault_key_src: "/home/admin/.lxv.key"

maintenance_password_filename: "SCRT_local_password_maintenance_password"

postgres_host_main_password_filename: "SCRT_roles_system_password_postgres_host_main_password"
postgres_host_test_password_filename: "SCRT_roles_system_password_postgres_host_test_password"

admin_vpn_ip: "172.16.255.106"
postgres_host_test_ip: "172.16.255.13"

ansible_groups:
  - "common"
group_roles: {}
group_services: {}
group_luxnix:
  generic_settings.vpnSubnet: '"172.16.255.0/24"'
  generic_settings.sensitiveServiceGroupName: '"sensitiveServices"'
  generic_settings.postgres.enable: "true"
  dns.enable: "true"
  generic_settings.enable: "true"
  generic_settings.linux.kernelPackages: "pkgs.linuxPackages_6_12"
  generic_settings.adminVpnIp: '"172.16.255.106"'
  generic_settings.traefikHostIp: '"172.16.255.12"'
  generic_settings.traefikHostDomain: '"traefik.endo-reg.net"'
  vault.enable: "true"
  vault.dir: '"/etc/secrets/vault"'
  vault.key: '"/etc/secrets/.key"' # Depreceated ?
  vault.psk: '"/etc/secrets/.psk"' # Depreceated ?

ansible_key_dir: "{{ luxnix_dest }}/secrets/ansible-vault-keys"
ansible_key_source_dir: "{{ luxnix_dev_repo }}/secrets/ansible-vault-keys-source"

luxnix_dev_repo: "/home/admin/dev/luxnix"
luxnix_repo: "https://github.com/wg-lux/luxnix.git"
luxnix_dest: "/home/admin/lx-production"
luxnix_branch: "main"
# luxnix_secrets: []

endoreg_db_repo: "https://github.com/wg-lux/endoreg-db.git"
endoreg_db_dest: "/home/admin/endoreg-db-production"
endoreg_db_branch: "main"

endoreg_db_api_repo: "https://github.com/wg-lux/endoreg-db-api.git"
endoreg_db_api_dest: "/home/admin/endoreg-db-api-production"
endoreg_db_api_branch: "main"

ansible_user: admin
ansible_become_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: "{{ luxnix_dest }}/.devenv/state/venv/bin/python"

local_users_passwords_dir: "{{ luxnix_dest }}/secrets/user-passwords/{{ inventory_hostname }}"
admin_password_file: "{{ local_users_passwords_dir }}/admin_raw"
# admin_password_file_source: "{{ luxnix_dev_repo }}/secrets/user-passwords/{{ inventory_hostname }}/admin_raw"
admin_password_file_source: "{{ lx_vault_dir_src }}/secrets/password/local/admin@{{ inventory_hostname }}/admin@{{ inventory_hostname }}_password"

authentication:
  dev_01:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEh2Bg+mSSvA80ALScpb81Q9ZaBFdacdxJZtAfZpwYkK
  dev_02: {} # Add gc-05 pubkey here
  dev_03:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDBJcYjGNIwOUs+KG8TbBxPWtJFEqni0p+1J5Yz++Aos
  agl_admin:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM7vvbgQtzi4GNeugHSuMyEke4MY0bSfoU7cBOnRYU8M

network_conf:
  domain: "endo-reg.net"

aglnet_conf:
  domain: "{{ network_conf.domain }}"
  subnet: "172.16.255.0"
  subnetIntern: "255.255.255.0"
  subnetSuffix: "32"
  caPath: "/etc/openvpn/ca.pem"
  tlsAuthPath: "/etc/openvpn/tls.pem"
  serverCertPath: "/etc/openvpn/crt.crt"
  serverKeyPath: "/etc/openvpn/key.key"
  dhPath: "/etc/openvpn/dh.pem"
  clientConfigDir: "/etc/openvpn/ccd"
  backupNameservers:
    - "8.8.8.8"
    - "1.1.1.1"
