# inventory/group_vars/all.yml
---
secret_dir: "/etc/secrets"
lx_vault_dir: "{{ secret_dir }}/vault"
lx_vault_key: "{{ secret_dir }}/.key"
lx_vault_psk: "{{ secret_dir }}/.psk"
lx_vault_dir_src: "/home/admin/.lxv"
lx_vault_key_src: "/home/admin/.lxv.key"
lx_vault_host_deploy_dir: "{{ lx_vault_dir_src }}/deploy/{{ inventory_hostname }}"

# admin_password_file: "{{ local_users_passwords_dir }}/admin_raw"
# admin_password_hashed_file: "{{ local_users_passwords_dir }}/admin_hashed"

maintenance_password_filename: "SCRT_local_password_maintenance_password"
admin_password_filename: "SCRT_local_password_admin_password"
admin_password_hashed_filename: "{{ admin_password_filename }}_hash"
postgres_host_main_password_filename: "SCRT_roles_system_password_postgres_host_main_password"
postgres_host_test_password_filename: "SCRT_roles_system_password_postgres_host_test_password"

admin_vpn_ip: "172.16.255.106"
postgres_host_test_ip: "172.16.255.13"

ansible_groups:
  - "common"
group_roles:
  custom_packages.enable: "true"
  custom_packages.cloud: "true"
  common.enable: "true"
group_services: {}
group_luxnix:
  generic_settings.network.nginx.vpnIp: '"172.16.255.12"'
  generic_settings.network.keycloak.domain: '"keycloak.endo-reg.net"'
  generic_settings.network.keycloak.adminDomain: '"adminKeycloak.endo-reg.net"'
  generic_settings.network.keycloak.vpnIp: '"172.16.255.12"'
  generic_settings.network.keycloak.port: "8443"
  generic_settings.network.nextcloud.vpnIp: '"172.16.255.13"'
  generic_settings.network.nextcloud.domain: '"cloud.endo-reg.net"'
  generic_settings.network.psqlMain.vpnIp: '"172.16.255.12"'
  generic_settings.network.psqlMain.port: "5432"
  # generic_settings.network.psqlMain.domain: '"psql-main.endo-reg.net"'
  # generic_settings.network.psqlTest.vpnIp: '"172.16.255.13"'
  # generic_settings.network.psqlTest.port: "5432"
  generic_settings.network.psqlTest.domain: '"psql-test.endo-reg.net"'
  generic-settings.sslCertificatePath: '"/etc/secrets/vault/ssl_cert"'
  generic-settings.sslCertificateKeyPath: '"/etc/secrets/vault/ssl_key"'
  generic-settings.smtpUserFilePath: '"/etc/secrets/vault/smtp_user"'
  generic-settings.smtpPwdFilePath: '"/etc/secrets/vault/smtp_pwd"'

  generic_settings.vpnSubnet: '"172.16.255.0/24"'
  generic_settings.sensitiveServiceGroupName: '"sensitiveServices"'
  generic_settings.postgres.enable: "true"
  dns.enable: "true"
  generic_settings.enable: "true"
  generic_settings.linux.kernelPackages: "pkgs.linuxPackages_6_12"
  generic_settings.adminVpnIp: '"172.16.255.106"'
  generic_settings.traefikHostIp: '"172.16.255.12"'
  generic_settings.traefikHostDomain: '"traefik.endo-reg.net"'
  vault.enable: "true"
  vault.dir: '"/etc/secrets/vault"'
  vault.key: '"/etc/secrets/.key"' # Depreceated ?
  vault.psk: '"/etc/secrets/.psk"' # Depreceated ?

ansible_key_dir: "{{ luxnix_dest }}/secrets/ansible-vault-keys"
ansible_key_source_dir: "{{ luxnix_dev_repo }}/secrets/ansible-vault-keys-source"

luxnix_dev_repo: "/home/admin/dev/luxnix"
luxnix_repo: "https://github.com/wg-lux/luxnix.git"
luxnix_dest: "/home/admin/lx-production"
luxnix_branch: "main"
# luxnix_secrets: []

endoreg_db_repo: "https://github.com/wg-lux/endoreg-db.git"
endoreg_db_dest: "/home/admin/endoreg-db-production"
endoreg_db_branch: "main"

endoreg_db_api_repo: "https://github.com/wg-lux/endoreg-db-api.git"
endoreg_db_api_dest: "/home/admin/endoreg-db-api-production"
endoreg_db_api_branch: "main"

ansible_user: admin
ansible_become_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: "{{ luxnix_dest }}/.devenv/state/venv/bin/python"

authentication:
  dev_01:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEh2Bg+mSSvA80ALScpb81Q9ZaBFdacdxJZtAfZpwYkK
  dev_02: {} # Add gc-05 pubkey here
  dev_03:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDBJcYjGNIwOUs+KG8TbBxPWtJFEqni0p+1J5Yz++Aos
  agl_admin:
    id_ed25519_pub: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM7vvbgQtzi4GNeugHSuMyEke4MY0bSfoU7cBOnRYU8M

network_conf:
  domain: "endo-reg.net"

aglnet_conf:
  domain: "{{ network_conf.domain }}"
  subnet: "172.16.255.0"
  subnetIntern: "255.255.255.0"
  subnetSuffix: "32"
  caPath: "/etc/openvpn/ca.pem"
  tlsAuthPath: "/etc/openvpn/tls.pem"
  serverCertPath: "/etc/openvpn/crt.crt"
  serverKeyPath: "/etc/openvpn/key.key"
  dhPath: "/etc/openvpn/dh.pem"
  clientConfigDir: "/etc/openvpn/ccd"
  backupNameservers:
    - "8.8.8.8"
    - "1.1.1.1"
