group_roles:
  aglnet.client.enable: "true"
  base_server.enable: "true"
  gpu_server.enable: "true"
group_services: {}
group_luxnix:
  nvidia_default.enable: "true"
  maintenance.autoUpdates.enable: "false"
  maintenance.autoUpdates.operation: '"switch"'
  maintenance.autoUpdates.flake: '"github:wg-lux/luxnix/datahub"'
  maintenance.autoUpdates.dates: '"06:00"'
