keys:
  # if not specified otherwise the keys are for admin@hostname
  - &primary age1ql756kedfz8tnt0hn5er7cwhvf4zm8h2wurl06ze4gvhgk5ur36skqvymv
  - &s-02 age1jx8m3ck3cct0p99rx7llnxnzrwl5gg4g3vcg2m7fddqprusn8p4qndp5er
  - &gc-06 age1jx8m3ck3cct0p99rx7llnxnzrwl5gg4g3vcg2m7fddqprusn8p4qndp5er


creation_rules:
  # Postgres Main
  ## Full Access
  - path_regex: secrets/postgres-main/host.json
    key_groups:
      - age:
        - *primary
        - *s-02
        - *gc-06

  ## Client Access
  - path_regex: secrets/postgres-main/client.json
    key_groups:
      - age:
        - *primary
        - *s-02
        - *gc-06

  # should be last rule in the list to prevent
  # premature matching
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|txt|tmp|bin|key|crt|pem)$
    key_groups:
      - age:
        - *primary
        - *gc-06