[project]
name = "luxnix"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
HOME_DIR = {description = "HOME_DIR secret", required = true}

CONFIG_DIR = {description = "CONFIG_DIR secret", default = "{HOME_DIR}/.config", required = false}
WORKING_DIR = {description = "WORKING_DIR secret", required = true}

STORAGE_FAST_ROOT = {description = "STORAGE_FAST_ROOT secret", default = "{WORKING_DIR}/data/storage-fast", required = false}
STORAGE_PERSISTING_EXTERNAL_DRIVE = {description = "STORAGE_PERSISTING_EXTERNAL_DRIVE", default = "false", required = false}
STORAGE_PERSISTING_HDD_ID = {description = "STORAGE_PERSISTING_HDD_ID secret", default = "", required = false}
STORAGE_PERSISTING_HDD_PART = {description = "STORAGE_PERSISTING_HDD_PART secret", default = "part1", required = false}
STORAGE_PERSISTING_MOUNT_POINT = {description = "STORAGE_PERSISTING_MOUNT_POINT secret", default = "{WORKING_DIR}/data/storage-persisting", required = false}
# DATABASE_URL = { description = "Database connection string", required = true }

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
