all:
  # vars:  # Global variables
  #   ansible_user: "admin"
  #   ansible_ssh_private_key_file: "/path/to/private/key"
  children:
    basic_servers:
      children:
        openvpn:
          hosts:
            s-01:
              openvpnIp: "172.16.255.1"
              services:
                - name: "traefik"
                  description: "Reverse proxy for *.endo-reg.net"
                  enabled: true
                - name: "openvpn"
                  description: "Primary VPN host"
                  enabled: true
        traefik:
          hosts:
            s-01: {}
        postgres-main:
          hosts:
            s-02:
              openvpnIp: "172.16.255.12"
              services:
                - name: "postgres"
                  description: "Main production DB"
                  enabled: true
        keycloak:
          hosts:
            s-03:
              openvpnIp: "172.16.255.13"
              services:
                - name: "postgres"
                  description: "Backup DB"
                  enabled: true
                - name: "keycloak"
                  description: "Keycloak SSO server"
                  enabled: true
        postgres-backup:
          hosts:
            s-03: {}
        postgres-test:
          hosts:
            s-04:
              openvpnIp: "172.16.255.14"
              services:
                - name: "postgres"
                  description: "Testing DB"
                  enabled: true
    gpu_servers:
      hosts:
        gs-01:
          openvpnIp: "172.16.255.21"
          roles: ["gpu-server"]
        gs-02:
          openvpnIp: "172.16.255.22"
          roles: ["gpu-server"]
    gpu_clients:
      hosts:
        gc-01:
          openvpnIp: "172.16.255.101"
        gc-02:
          openvpnIp: "172.16.255.102"
        gc-03:
          openvpnIp: "172.16.255.103"
        gc-04:
          openvpnIp: "172.16.255.104"
        gc-05:
          openvpnIp: "172.16.255.105"
        gc-06:
          openvpnIp: "172.16.255.106"
        gc-07:
          openvpnIp: "172.16.255.107"
        gc-08:
          openvpnIp: "172.16.255.108"
        gc-09:
          openvpnIp: "172.16.255.109"
    users:
      vars:
        default_users:
          - username: "admin"
            permissions: { read: true, write: true, execute: true }
          - username: "dev-01"
            permissions: { read: true, write: true, execute: true }
          - username: "user"
            permissions: { read: true, write: false, execute: false }
        additional_users:
          - username: "lux_t"
            permissions: { read: true, write: true, execute: false }
          - username: "d01"
            permissions: { read: true, write: true, execute: true }
          - username: "d02"
            permissions: { read: true, write: true, execute: true }
