{
  # Generated by luxnix-render-boot-decryption-config; do not edit directly.
  boot.initrd.availableKernelModules = [
    "dm-crypt"
    "sd_mod"
    "usb_storage"
  ];

  boot.initrd.luks.devices = {
    "cryptroot" = {
      keyFile = "/dev/disk/by-uuid/ea642a66-fc4e-448f-81a3-97ed2dd3ccd3";
      keyFileOffset = 52428800;
      keyFileSize = 4096;
      preLVM = true;
      keyFileTimeout = 10; # If no prompt is displayed, try pressing Esc.
    };
  };
}
