# inventory/host_vars/gc-02.yml
---
template_name: "gpu-client-dev"
primary_group: "gpu_client"
nvidia_prime:
  nvidiaBusId: "PCI:1:0:0"
  onboardBusId: "PCI:0:2:0"
  onboardGpuType: "intel"

host_roles: []
host_services: []

generic_settings:
  hostPlatform: "x86_64-linux"
  systemStateVersion: "23.11" 

  linux:
    cpuMicrocode: "intel"

    kernelPackages: "pkgs.linuxPackages_latest"
    kernelModules:
      - "kvm-intel"
    initrd:
      supportedFilesystems:
        - "nfs"
      kernelModules:
        - "nfs"
      availableKernelModules:
        - "xhci_pci"
        - "ahci"
        - "nvme"
        - "usb_storage"
        - "sd_mod"
    supportedFilesystems:
      - "btrfs"
    resumeDevice: "/dev/disk/by-label/nixos"
    kernelParams: []
    kernelModulesBlacklist: []
