# inventory/host_vars/gc-07.yml
---
template_name: "main"
host_roles:
  aglnet.client.enable: "true"

host_services: {}

host_luxnix:
  generic_settings.hostPlatform: "x86_64-linux"
  generic_settings.systemStateVersion: "23.11"
  generic_settings.linux.cpuMicrocode: "intel"
  generic_settings.linux.kernelPackages: "pkgs.linuxPackages_latest"
  generic_settings.linux.kernelModules:
    - "kvm-intel"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
  generic_settings.linux.initrd.availableKernelModules:
    - "vmd"
    - "xhci_pci"
    - "ahci"
    - "nvme"
    - "usb_storage"
    - "sd_mod"
  generic_settings.linux.supportedFilesystems:
    - "btrfs"
  generic_settings.linux.resumeDevice: "/dev/disk/by-label/nixos"
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
  nvidia_prime:
    nvidiaBusId: "PCI:1:0:0"
    onboardBusId: "PCI:0:2:0"
    onboardGpuType: "intel"
