# inventory/host_vars/gc-07.yml
---
template_name: "main"
host_roles:
  custom_packages.cuda: "true"
  custom_packages.office: "true"
  custom_packages.baseDevelopment: "true"
host_services: {}

extra_secret_names:
  - "SCRT_roles_system_password_postgres_host_test_password"

host_luxnix:
  generic_settings.hostPlatform: '"x86_64-linux"'
  generic_settings.systemStateVersion: '"23.11"'
  generic_settings.linux.cpuMicrocode: '"intel"'
  generic_settings.vpnIp: '"172.16.255.107"'

  generic_settings.linux.kernelModules:
    - "intel"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.availableKernelModules:
    - "vmd"
    - "xhci_pci"
    - "ahci"
    - "nvme"
    - "usb_storage"
    - "sd_mod"
  generic_settings.linux.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.resumeDevice: '"/dev/disk/by-label/nixos"'
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
  nvidia_prime.nvidiaBusId: '"PCI:1:0:0"'
  nvidia_prime.onboardBusId: '"PCI:0:2:0"'
  nvidia_prime.onboardGpuType: '"intel"'
