# inventory/host_vars/gc-08.yml
---
template_name: "main"

host_roles:
  aglnet.client.enable: "true"
  custom_packages.dev03: "true"
  custom_packages.cuda: "true"
  custom_packages.office: "true"
  custom_packages.baseDevelopment: "true"

host_services: {}

host_luxnix:
  generic_settings.hostPlatform: '"x86_64-linux"'
  generic_settings.systemStateVersion: '"23.11"'

  generic_settings.linux.cpuMicrocode: '"intel"'
  generic_settings.linux.kernelPackages: "pkgs.linuxPackages_latest"
  generic_settings.linux.kernelModules:
    - "intel"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.availableKernelModules:
    - "vmd"
    - "xhci_pci"
    - "ahci"
    - "nvme"
    - "usb_storage"
    - "sd_mod"
  generic_settings.linux.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.resumeDevice: '"/dev/disk/by-label/nixos"'
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
  nvidia_prime.nvidiaBusId: '"PCI:1:0:0"'
  nvidia_prime.onboardBusId: '"PCI:0:2:0"'
  nvidia_prime.onboardGpuType: '"intel"'
