# inventory/host_vars/gs-01.yml
---
template_name: "main"

host_roles:
  aglnet.client.enable: "true"

host_services: {}

host_luxnix:
  generic_settings.hostPlatform: "x86_64-linux"
  generic_settings.systemStateVersion: "23.11"

  generic_settings.linux.cpuMicrocode: "amd"

  generic_settings.linux.kernelPackages: "pkgs.linuxPackages_latest"
  generic_settings.linux.kernelModules:
    - "kvm-amd"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
    - "dm-snapshot"
  generic_settings.linux.initrd.availableKernelModules:
    - "xhci_pci"
    - "ahci"
    - "mpt3sas"
    - "usb_storage"
    - "usbhid"
    - "sd_mod"

  generic_settings.linux.supportedFilesystems:
    - "btrfs"
  generic_settings.linux.resumeDevice: "/dev/disk/by-label/nixos"
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
