# inventory/host_vars/gs-01.yml
---
template_name: "main"

host_roles: {}

host_services: {}

host_luxnix:
  boot_decryption_stick_gs_01.enable: "true"
  generic_settings.vpnIp: '"172.16.255.22"'

  generic_settings.hostPlatform: '"x86_64-linux"'
  generic_settings.systemStateVersion: '"23.11"'

  generic_settings.linux.cpuMicrocode: '"amd"'

  generic_settings.linux.kernelModules:
    - "kvm-amd"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
    - "btrfs"
    - "dm-snapshot"
  generic_settings.linux.initrd.availableKernelModules:
    - "xhci_pci"
    - "ahci"
    - "thunderbolt"
    - "nvme"
    - "usb_storage"
    - "usbhid"
    - "sd_mod"

  generic_settings.linux.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.resumeDevice: '"/dev/disk/by-label/nixos"'
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
