# inventory/host_vars/gs-01.yml
---
template_name: "gpu-server"
primary_group: "gpu_server"

host_roles: []
host_services: []

generic_settings:
  hostPlatform: "x86_64-linux"
  systemStateVersion: "23.11" 

  linux:
    cpuMicrocode: "amd"

    kernelPackages: "pkgs.linuxPackages_latest"
    kernelModules:
      - "kvm-amd"
    initrd:
      supportedFilesystems:
        - "nfs"
      kernelModules:
        - "nfs"
        - "dm-snapshot"
      availableKernelModules:
        # [ "xhci_pci" "ahci" "mpt3sas" "usb_storage" "usbhid" "sd_mod" ];
        - "xhci_pci"
        - "ahci"
        - "mpt3sas"
        - "usb_storage"
        - "usbhid"
        - "sd_mod"

    supportedFilesystems:
      - "btrfs"
    resumeDevice: "/dev/disk/by-label/nixos"
    kernelParams: []
    kernelModulesBlacklist: []
