# inventory/host_vars/h-01.yml
---
template_name: "hetzner-server"
primary_group: "hetzner_server"

host_roles: 
  - name: "aglnet.client"

host_services: []

generic_settings:
  hostPlatform: "x86_64-linux"
  systemStateVersion: "23.11" 

  linux:
    cpuMicrocode: "amd"

    kernelPackages: "pkgs.linuxPackages_latest"
    kernelModules:
      - "kvm-amd"
    initrd:
      supportedFilesystems:
        - "nfs"
      kernelModules:
        - "nfs"
      availableKernelModules:
        # [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "usb_storage" "sd_mod" ];
        - "xhci_pci"
        - "uas"
        - "ahci"
        - "usbhid"
        - "nvme"
        - "usb_storage"
        - "sd_mod"
    supportedFilesystems:
      - "btrfs"
    resumeDevice: "/dev/disk/by-label/nixos"
    kernelParams: []
    kernelModulesBlacklist: []
