# inventory/host_vars/s-02.yml
---
template_name: "main"

ansible_roles:
  - postgres_host_main
  - nginx_host
  - keycloak_host
  - nextcloud_host
  - ssl_cert

host_roles: {}
host_services: {}

host_luxnix:
  generic_settings.hostPlatform: '"x86_64-linux"'
  generic_settings.systemStateVersion: '"23.11"'
  generic_settings.vpnIp: '"172.16.255.12"'

  generic_settings.linux.cpuMicrocode: '"intel"'

  generic_settings.linux.kernelModules:
    - "kvm-intel"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.availableKernelModules:
    - "xhci_pci"
    - "ahci"
    - "usbhid"
    - "nvme"
    - "usb_storage"
    - "sd_mod"
  generic_settings.linux.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.resumeDevice: '"/dev/disk/by-label/nixos"'
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
  # ssh-access.dev-01.enable: "true"
  # ssh-access.dev-01.idEd25519: '"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEh2Bg+mSSvA80ALScpb81Q9ZaBFdacdxJZtAfZpwYkK"'
