# inventory/host_vars/s-02.yml
---
template_name: "main"

host_roles: {}

host_services: {}

luxnix_branch: "postgres-implementation"

ansible_roles: []

host_luxnix:
  generic_settings.enable: "true"
  generic_settings.hostPlatform: '"x86_64-linux"'
  generic_settings.systemStateVersion: '"23.11"'

  generic_settings.linux.cpuMicrocode: '"amd"'

  generic_settings.linux.kernelModules:
    - "kvm-amd"
  generic_settings.linux.initrd.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.kernelModules:
    - "nfs"
    - "btrfs"
  generic_settings.linux.initrd.availableKernelModules:
    - "xhci_pci"
    - "ahci"
    - "usbhid"
    - "nvme"
    - "usb_storage"
    - "sd_mod"
  generic_settings.linux.supportedFilesystems:
    - "nfs"
    - "btrfs"
  generic_settings.linux.resumeDevice: '"/dev/disk/by-label/nixos"'
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
