# inventory/host_vars/s-04.yml
---
template_name: "main"
ansible_roles:
  - "dev_access"
host_roles:
  aglnet.client.enable: "true"
  endoreg_client.enable: "true" # Manual override of false in base_server.yml

host_services: {}
host_luxnix:
  generic_settings.hostPlatform: '"x86_64-linux"'
  generic_settings.systemStateVersion: '"23.11"'
  generic_settings.linux.cpuMicrocode: '"intel"'
  nvidia_prime.enable: "lib.mkForce false"

  generic_settings.linux.kernelModules:
    - "kvm-intel"
  generic_settings.linux.initrd.supportedFilesystems:
    - "btrfs"
    - "nfs"
  generic_settings.linux.initrd.kernelModules:
    - "btrfs"
    - "nfs"
  generic_settings.linux.initrd.availableKernelModules:
    - "xhci_pci"
    - "uas"
    - "ahci"
    - "usbhid"
    - "nvme"
    - "usb_storage"
    - "sd_mod"
    - "sdhci_pci"
  generic_settings.linux.supportedFilesystems:
    - "btrfs"
    - "nfs"
  generic_settings.linux.resumeDevice: '"/dev/disk/by-label/nixos"'
  generic_settings.linux.kernelParams: []
  generic_settings.linux.kernelModulesBlacklist: []
