from __future__ import annotations

from pathlib import Path


OPTIONS_NIX = Path(
    "/home/admin/dev/luxnix/modules/nixos/services/lx-annotate-local/options.nix"
)
CONFIG_NIX = Path(
    "/home/admin/dev/luxnix/modules/nixos/services/lx-annotate-local/config.nix"
)


def test_lx_annotate_module_declares_auto_generated_master_key_options():
    source = OPTIONS_NIX.read_text(encoding="utf-8")

    assert "autoGenerateMasterKey = mkOption" in source
    assert "default = true;" in source
    assert "autoGeneratedMasterKeyFilePath = mkOption" in source
    assert 'default = "/etc/secrets/vault/lx_annotate_master_key";' in source


def test_lx_annotate_module_wires_per_machine_master_key_generation():
    source = CONFIG_NIX.read_text(encoding="utf-8")

    assert "roles.managed-secrets.customSecrets.lx_annotate_master_key_local" in source
    assert (
        "Per-machine application master key for lx-annotate encrypted storage" in source
    )
    assert "${pkgs.openssl}/bin/openssl rand -base64 32 | tr -d '\\n'" in source
    assert "cfg.runtime.autoGenerateMasterKey" in source
