keycloak_host_password_filename: "SCRT_roles_system_password_keycloak_host_password"
keycloak_host_pw_src: "{{ lx_vault_dir_src }}/deploy/{{ inventory_hostname }}/{{ keycloak_host_password_filename }}"

keycloak_host_roles:
  keycloakHost.enable: "true"
  keycloakHost.adminUsername: '"admin"'
  keycloakHost.adminInitialPassword: '"admin"'
  keycloakHost.homeDir: '"/etc/keycloak"'
  keycloakHost.dbUsername: '"keycloak"'
  keycloakHost.dbPasswordfile: '"SCRT_roles_system_password_keycloak_host_password"' # Same as keycloak_host_password_filename
