keycloak_host_roles:
  keycloakHost.enable: "true"
  keycloakHost.httpPort: "9080"
  keycloakHost.httpsPort: "9443"
  keycloakHost.adminUsername: '"admin"'
  keycloakHost.adminInitialPassword: '"admin"'
  keycloakHost.dbUsername: '"keycloak"'
  keycloakHost.dbPasswordfile: '"/etc/secrets/vault/SCRT_roles_system_password_keycloak_host_password"'
  keycloakHost.hostname: '"keycloak.endo-reg.net"'
  keycloakHost.hostnameAdmin: '"keycloak-admin.endo-reg.net"'
  keycloakHost.vpnIP: '"172.16.255.12"'
