keycloak_host_password_filename: "keycloak-db-password"
keycloak_host_psql_keycloak_pw_file: /etc/secrets/vault/{{ keycloak_host_psql_keycloak_pw_file }}
keycloak_host_psql_keycloak_pw_src: /home/admin/.lxv/deploy/{{ inventory_hostname }}/{{ keycloak_host_psql_keycloak_pw_file }}

keycloak_host_roles:
  keycloakHost.enable: "true"
  keycloakHost.httpPort: "9080"
  keycloakHost.httpsPort: "9444"
  keycloakHost.adminUsername: '"admin"'
  keycloakHost.adminInitialPassword: '"admin"'
  keycloakHost.homeDir: '"/etc/keycloak"'
  keycloakHost.dbUsername: '"keycloak"'
  keycloakHost.dbPasswordfile: '"keycloak-db-password"'
  keycloakHost.hostname: '"keycloak.endo-reg.net"'
  keycloakHost.vpnIP: '"172.16.255.12"'
