apiVersion: v1
kind: Secret
metadata:
  name: lx-annotate-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: replace-with-django-secret-key
  DJANGO_DB_PASSWORD: replace-with-postgres-password
  OIDC_RP_CLIENT_ID: lx-annotate
  OIDC_RP_CLIENT_SECRET: replace-with-oidc-client-secret
  master-key: replace-with-shared-workload-master-key
