{
  # Generated by luxnix-render-boot-decryption-config; do not edit directly.
  boot.initrd.availableKernelModules = [
    "dm-crypt"
    "sd_mod"
    "usb_storage"
  ];

  boot.initrd.luks.devices = {
    "cryptroot" = {
      keyFile = "/dev/disk/by-uuid/6eb5de91-8143-4a19-9f59-a4e0f721424b";
      keyFileOffset = 52428800;
      keyFileSize = 4096;
      preLVM = true;
      keyFileTimeout = 10; # If no prompt is displayed, try pressing Esc.
    };
  };
}
