- name: Make sure the target directory exists
  ansible.builtin.file: # filepath = "{{ local_users_passwords_dir  }}"
    path: "{{ local_users_passwords_dir }}"
    state: directory
    owner: "{{ ansible_become_user }}"
    mode: "0700"
  no_log: true

- name: Copy passwordfile to target machine
  ansible.builtin.copy:
    src: "{{ admin_password_file_source }}"
    dest: "{{ admin_password_file }}"
    mode: "0600"
    owner: "{{ ansible_become_user }}"
  register: user_password
  no_log: true
