- name: Copy passwordfile to target machine
  ansible.builtin.copy:
    src: "{{ managed_admin_password_file_source }}"
    dest: "{{ lx_vault_dir }}/{{ admin_password_filename }}"
    mode: "0600"
    owner: "{{ ansible_become_user }}"
  register: user_password
  no_log: false
  vars:
    ansible_vault_identity: "{{ inventory_hostname }}@{{ lx_vault_dir_src }}/psk/{{ inventory_hostname }}.psk"

- name: Copy passwordfile (hashed) to target machine
  ansible.builtin.copy:
    src: "{{ managed_admin_password_hashed_source }}"
    dest: "{{ lx_vault_dir }}/{{ admin_password_hashed_filename }}"
    mode: "0600"
    owner: "{{ ansible_become_user }}"
  register: user_password
  no_log: false
  vars:
    ansible_vault_identity: "{{ inventory_hostname }}@{{ lx_vault_dir_src }}/psk/{{ inventory_hostname }}.psk"
