- name: Read admin password
  ansible.builtin.slurp:
    src: "{{ lx_vault_dir }}/{{ admin_password_filename }}"
  register: user_password
  no_log: false
  vars:
    ansible_vault_identity: "{{ inventory_hostname }}@{{ lx_vault_dir_src }}/psk/{{ inventory_hostname }}.psk"

# - name: Debug user password
#   ansible.builtin.debug:
#     msg: "User password: {{ user_password.content | b64decode }}"

- name: Clone or update the wg-lux/luxnix repository
  ansible.builtin.git:
    repo: "{{ luxnix_repo }}"
    dest: "{{ luxnix_dest }}"
    version: "{{ luxnix_branch }}"
    update: true
    force: false
  register: git_update
  notify:
    - Run nho
    - Run nhh
