---
host_home_cli:
  cli.programs.git.userName: "Hamzaukw"
  cli.programs.git.email: "hamza.ukw@gmail.com"
  cli.programs.git.allowedSigners: " SHA256:nN5Ha+k2duMh/XZnKqa3Bs7jkUorUpsKzF+aqhTMMGg "

host_home_roles:
  social.enable: true
  gpu.enable: true
  development.enable: true
  video.enable: true
host_home_luxnix:
  luxnix.generic-settings.hostPlatform: "x86_64-linux"
