host_home_cli:
  cli.programs.git.userName: "PeterKczyk"
  cli.programs.git.email: "peter.kowalczyk21@gmail.com"

host_home_luxnix:
  luxnix.generic-settings.enable: true
  luxnix.generic-settings.configurationPath: "dev/luxnix"
  luxnix.generic-settings.language: "english"
  luxnix.generic-settings.hostPlatform: '"x86_64-linux"'
