host_home_cli:
  cli.programs.git.userName: "maddonix"
  cli.programs.git.email: "tlux14@googlemail.com"
  cli.programs.git.allowedSigners: "SHA256:LNfWnvEthO0QL8DzUxtxHD4VnLxvCZWFmcDhZodk29o"

host_home_networking:
  networking.usePredictableInterfaceNames: false

  systemd.network.enable: true
  systemd.network.networks."eth0".extraConfig: |
    [Match]
    Name = eth0
    [Network]
    Address = 2a01:4f8:a0:93ba::/64
    Gateway = fe80::1
    # optionally you can do the same for ipv4 and disable DHCP (networking.dhcpcd.enable = false;)
    # Address =  144.x.x.x/26
    # Gateway = 144.x.x.1


# No luxnix.generic-settings present — nothing to add

 # luxnix.django-demo-app = {
  #   enable = true;
  # };
# Re-uses ssh host keys from the sshd to not break .ssh/known_hosts
# Authorized ssh keys are read from /root/.ssh/authorized_keys, /root/.ssh/authorized_keys2 and /etc/ssh/authorized_keys.d/root

host_home_luxnix:
  luxnix.generic-settings.hostPlatform: '"x86_64-linux"'
