---
- name: Deploy Secrets (Full Pipeline)
  hosts: managed
  gather_facts: false
  become: true # Ensures tasks run with elevated privileges (root)
  become_user: admin # Optional if 'become' defaults to root on your system

  tasks:
    - name: Copy PSK file
      ansible.builtin.copy:
        src: "{{ lx_vault_dir_src }}/psk/{{ inventory_hostname }}.psk"
        dest: "{{ lx_vault_psk }}"
        mode: "0600"
        owner: "{{ ansible_user }}"
      no_log: true

    - name: Load deployment configuration
      ansible.builtin.include_vars:
        file: "{{ lx_vault_dir_src }}/deploy/{{ inventory_hostname }}.yml"
        name: deploy_config

    - name: Deploy each key
      ansible.builtin.include_tasks: "./deploy_key.yml"
      loop: "{{ deploy_config.access_keys }}"
      loop_control:
        loop_var: item
