---
- name: Deploy Secrets (Full Pipeline)
  hosts: managed
  gather_facts: false
  become: true
  become_user: admin

  tasks:
    - name: Copy PSK file
      ansible.builtin.copy:
        src: "{{ lx_vault_dir_src }}/psk/{{ inventory_hostname }}.psk"
        dest: "{{ lx_vault_psk }}"
        mode: "0600"
        owner: "{{ ansible_user }}"
      no_log: true

    - name: Find all secret files
      ansible.builtin.find:
        paths: "{{ lx_vault_dir_src }}/deploy/{{ inventory_hostname }}"
        recurse: true
      register: secret_files
      delegate_to: localhost

    - name: Deploy secrets individually
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ lx_vault_dir }}/{{ item.path | basename }}"
        mode: "0600"
        owner: "{{ ansible_user }}"
      loop: "{{ secret_files.files }}"
      no_log: true
      vars:
        ansible_vault_identity: "{{ inventory_hostname }}@{{ lx_vault_dir_src }}/psk/{{ inventory_hostname }}.psk"
