# schemas/network_config.schema.yaml
$schema: "http://json-schema.org/draft-07/schema#"
type: "object"
properties:
  networkName:
    type: "string"
  systems:
    type: "array"
    items:
      type: "object"
      properties:
        hostname:
          type: "string"
          pattern: "^(s|gs|gc|ss)-[0-9]{2}$"
        openvpnIp:
          type: "string"
          pattern: "^172\\.16\\.255\\.[0-9]{1,3}$"
        roles:
          type: "array"
          items:
            type: "string"
        services:
          type: "array"
          items:
            type: "object"
            properties:
              name:
                type: "string"
              description:
                type: "string"
              enabled:
                type: "boolean"
            required: ["name", "enabled"]
        # Additional optional fields for dynamic usage
      required: ["hostname", "openvpnIp", "roles", "services"]
  users:
    type: "array"
    items:
      type: "object"
      properties:
        username:
          type: "string"
        defaultUser:
          type: "boolean"
        permissions:
          type: "object"
          additionalProperties:
            type: "boolean"
      required: ["username", "defaultUser"]
required:
  - networkName
  - systems
  - users
