args@{ lib, ... }:
with lib;
with lib.luxnix;
with args;
let
  runtime = lxAnnotateRuntime;
  inherit (runtime.identities)
    endoreg-service-user-name
    endoreg-service-group-name;
  inherit (runtime.helpers) mkDjangoOptions;
  inherit (runtime.defaults) externalCleanupArchiveRootDefault;
  inherit (runtime.paths)
    runtimeDataRootPath
    dataRecoveryStateFile
    hubBackupIncomingPath
    hubBackupSnapshotPath
    hubBackupManifestPath
    legacyRepoDataRootPath
    legacyRepoMediaRootPath
    legacyDataProcessedReportDir
    legacyDataProcessedVideoDir
    legacyMediaProcessedReportDir
    legacyMediaProcessedVideoDir
    runtimeProcessedReportDir
    runtimeProcessedVideoDir;
in
{
  options.services.luxnix.lxAnnotateLocal = {
    enable = mkBoolOpt false "Enable LxAnnotate Service";

    # Debug configuration
    debug = mkOption {
      type = types.submodule {
        options = {
          enable = mkOption {
            type = types.bool;
            default = false;
            description = "Enable verbose debug output including sensitive file information. Should be disabled in production.";
          };
        };
      };
      default = { };
      description = "Debug configuration for lx-annotate-local.";
    };

    # Source/Repository configuration
    source = mkOption {
      type = types.submodule {
        options = {
          url = mkOption {
            type = types.str;
            default = "https://github.com/wg-lux/lx-annotate";
            description = "Git repository URL for the lx-annotate application.";
          };
          branch = mkOption {
            type = types.str;

            default = "test";
            description = "Git branch to checkout for lx-annotate.";
          };
          updateOnBoot = mkOption {
            type = types.bool;
            default = true;
            description = "Whether to update the lx-annotate repository on service start.";
          };
        };
      };
      default = { };
      description = "Repository configuration for lx-annotate.";
    };

    runtime = mkOption {
      type = types.submodule {
        options = {
          mode = mkOption {
            type = types.enum [ "repo" "wheel" ];
            default = "wheel";
            description = "How lx-annotate is started. 'repo' keeps the dev git/devenv flow; 'wheel' installs a configured Python wheel into a runtime virtualenv.";
          };
          wheelPath = mkOption {
            type = types.nullOr types.path;
            default = pkgs.fetchurl {
              url = "https://files.pythonhosted.org/packages/2e/20/f6fd812a923bd537d8db2dc47d05736eeceec9a96888546b86303bb5da3a/lx_annotate-0.3.7-py3-none-any.whl";
              hash = "sha256-OQ+kUv4X3DxVMsZusa7+X2wdI0FCU6mLUz6BiMuToNU=";
            };
            description = "Path to the lx-annotate wheel artifact used in wheel mode.";
          };
          wheelhousePath = mkOption {
            type = types.nullOr types.path;
            default = null;
            example = "/var/lib/lx-annotate/artifacts/wheelhouse";
            description = "Optional directory containing prebuilt dependency wheels. When set, wheel installs run with --no-index --find-links so the service does not resolve/download dependencies from the network during startup.";
          };
          encryptedDataDir = mkOption {
            type = types.str;
            default = "/var/lib/lx-annotate/data";
            description = "External encrypted runtime data directory. Must stay outside the repo/app path.";
          };
          encryptionService = mkOption {
            type = types.nullOr types.str;
            default = null;
            example = "lx-annotate-encrypted-data.service";
            description = "Optional systemd unit that unlocks or mounts the encrypted lx-annotate data directory before app services start.";
          };
          masterKeyFile = mkOption {
            type = types.nullOr types.path;
            default = null;
            description = "Optional secret file exported as LX_ANNOTATE_MASTER_KEY_FILE for encrypted storage access.";
          };
          autoGenerateMasterKey = mkOption {
            type = types.bool;
            default = true;
            description = "Generate a per-machine application master key when no explicit runtime.masterKeyFile is configured.";
          };
          autoGeneratedMasterKeyFilePath = mkOption {
            type = types.path;
            default = "/etc/secrets/vault/lx_annotate_master_key";
            description = "Local path where the auto-generated per-machine application master key is written.";
          };
          managedEncryptedData = mkOption {
            type = types.submodule {
              options = {
                enable = mkOption {
                  type = types.bool;
                  default = false;
                  description = "Manage / unlock the lx-annotate encrypted data directory with a local LUKS-backed systemd unit.";
                };
                luksUuid = mkOption {
                  type = types.nullOr types.str;
                  default = null;
                  description = "LUKS UUID opened by lx-annotate-encrypted-data.service.";
                };
                keyFile = mkOption {
                  type = types.nullOr types.path;
                  default = null;
                  description = "Key file used to unlock the encrypted data volume.";
                };
                luksUuidFile = mkOption {
                  type = types.nullOr types.path;
                  default = null;
                  description = "Optional file containing the LUKS UUID for the encrypted data volume.";
                };
                mapperName = mkOption {
                  type = types.str;
                  default = "lx-annotate-data";
                  description = "Device-mapper name used for the unlocked encrypted data volume.";
                };
                fsType = mkOption {
                  type = types.str;
                  default = "ext4";
                  description = "Filesystem type mounted for the encrypted lx-annotate data volume.";
                };
                mountOptions = mkOption {
                  type = types.listOf types.str;
                  default = [ "defaults" ];
                  description = "Mount options passed to the encrypted data volume mount.";
                };
                owner = mkOption {
                  type = types.str;
                  default = endoreg-service-user-name;
                  description = "Owner applied to the mounted encrypted data directory.";
                };
                group = mkOption {
                  type = types.str;
                  default = endoreg-service-group-name;
                  description = "Group applied to the mounted encrypted data directory.";
                };
                dirMode = mkOption {
                  type = types.str;
                  default = "0750";
                  description = "Permissions applied to the mounted encrypted data directory.";
                };
                after = mkOption {
                  type = types.listOf types.str;
                  default = [ "managed-secrets-setup.service" ];
                  description = "Additional units ordered before the encrypted data service starts.";
                };
                requires = mkOption {
                  type = types.listOf types.str;
                  default = [ "managed-secrets-setup.service" ];
                  description = "Additional units required by the encrypted data service.";
                };
              };
            };
            default = { };
            description = "Managed encrypted data mount configuration for lx-annotate.";
          };
          vaultManagedEncryptedData = mkOption {
            type = types.submodule {
              options = {
                enable = mkOption {
                  type = types.bool;
                  default = false;
                  description = "Fetch lx-annotate encrypted-data unlock material from Vault via managed-secrets.";
                };
                keyFilePath = mkOption {
                  type = types.path;
                  default = "/etc/secrets/vault/lx_annotate_luks.key";
                  description = "Local path where the Vault-backed LUKS key is written.";
                };
                luksUuidFilePath = mkOption {
                  type = types.path;
                  default = "/etc/secrets/vault/lx_annotate_luks.uuid";
                  description = "Local path where the Vault-backed LUKS UUID is written.";
                };
                masterKeyFilePath = mkOption {
                  type = types.path;
                  default = "/etc/secrets/vault/lx_annotate_master_key";
                  description = "Local path where the Vault-backed application master key is written.";
                };
                vaultPathTemplate = mkOption {
                  type = types.str;
                  default = "secret/data/nodes/{hostname}/lx-annotate";
                  description = "Vault KV path template. `{hostname}` is replaced with networking.hostName.";
                };
                vaultKeyField = mkOption {
                  type = types.str;
                  default = "luks_key";
                  description = "Field name in the Vault payload that contains the raw LUKS key material.";
                };
                vaultUuidField = mkOption {
                  type = types.str;
                  default = "luks_uuid";
                  description = "Field name in the Vault payload that contains the LUKS UUID.";
                };
                vaultMasterKeyField = mkOption {
                  type = types.str;
                  default = "app_master_key";
                  description = "Field name in the Vault payload that contains the application-layer master key.";
                };
                manageMasterKey = mkOption {
                  type = types.bool;
                  default = true;
                  description = "Whether to provision the application master key from the same hostname-scoped Vault payload.";
                };
                setupService = mkOption {
                  type = types.str;
                  default = "managed-secrets-setup.service";
                  description = "Systemd unit responsible for delivering the Vault-backed lx-annotate secret files.";
                };
              };
            };
            default = { };
            description = "Hostname-aware Vault-backed provisioning for lx-annotate encrypted data secrets.";
          };
          pythonPackage = mkOption {
            type = types.package;
            default = pkgs.python312;
            description = "Python interpreter used to create the runtime virtualenv in wheel mode.";
          };
          tessdataPrefix = mkOption {
            type = types.str;
            default = "/run/current-system/sw/share/tessdata";
            description = "TESSDATA_PREFIX exported to wheel-based services.";
          };
          pytorchAllocConf = mkOption {
            type = types.str;
            default = "expandable_segments:True";
            description = "PYTORCH_ALLOC_CONF exported to wheel-based services.";
          };
          commands = mkOption {
            type = types.submodule {
              options = {
                fileWatcher = mkOption {
                  type = types.nullOr types.str;
                  default = null;
                  description = "Shell command executed for the file watcher in wheel mode. Runs with LX_ANNOTATE_WHEEL_VENV and LX_ANNOTATE_WHEEL_APP_ROOT exported.";
                };
                exportFrames = mkOption {
                  type = types.nullOr types.str;
                  default = null;
                  description = "Shell command executed for export-frames in wheel mode. Runs with LX_ANNOTATE_WHEEL_VENV and LX_ANNOTATE_WHEEL_APP_ROOT exported.";
                };
                celeryWorker = mkOption {
                  type = types.nullOr types.str;
                  default = null;
                  description = "Shell command executed for the Celery worker in wheel mode. Runs with LX_ANNOTATE_WHEEL_VENV and LX_ANNOTATE_WHEEL_APP_ROOT exported.";
                };
              };
            };
            default = { };
            description = "Additional service commands used in wheel mode.";
          };
        };
      };
      default = { };
      description = "Runtime bootstrap configuration for lx-annotate.";
    };

    # Django configuration (passed from endoreg-client role)
    django = mkOption {
      type = types.submodule {
        options = mkDjangoOptions {
          defaults = {
            hostname = "lx-annotate.local";
            port = 8117;
            useHttps = false;
            sslCertificatePath = null;
            sslKeyPath = null;
            djangoAllowedHosts = [
              "lx-annotate.local"
              "127.0.0.1"
            ];
            corsAllowedOrigins = [
              "https://lx-annotate.local"
              "http://127.0.0.1"
            ];
            djangoDebug = false;
            djangoSecretKeyFile = "/etc/secrets/vault/django_secret_key";
            keycloakSecretFile = "/etc/secrets/vault/keycloak.env";
            keycloakClientId = "endoregdb-api";
            logLevel = "INFO";
            maxRequestSize = "100M";
            timeZone = "Europe/Berlin";
            language = "en-us";
            settingsProfile = "prod";
            settingsModule = null;
            djangoEnv = null;
            dataDir = "data";
            confDir = "conf";
            confTemplateDir = "conf_template";
            djangoModule = "lx_annotate";
            assetDir = "tests/assets";
            httpProtocol = "http";
            baseUrl = null;
            staticUrl = "/static/";
            mediaUrl = "/media/";
            runVideoTests = false;
            skipExpensiveTests = true;
            extraSettings = { };
          };
          includeKeycloak = true;
          logLevelType = types.str;
          httpProtocolType = types.str;
        };
      };
      default = { };
      description = "Django configuration options for lx-annotate.";
    };

    # Database configuration
	    database = mkOption {
      type = types.submodule {
        options = {
          host = mkOption {
            type = types.str;
            default = "lx-annotate.local";
          };
          port = mkOption {
            type = types.port;
            default = 5433;
          };
          name = mkOption {
            type = types.str;
            default = "lxAnnotateLocal";
          };
          user = mkOption {
            type = types.str;
            default = "lxAnnotateLocal";
          };
          passwordFile = mkOption {
            type = types.path;
            default = "/etc/secrets/vault/SCRT_local_password_maintenance_password";
          };
          sslMode = mkOption {
            type = types.str;
            default = "prefer";
          };
          endoregLocalUserPasswordFile = mkOption {
            type = types.path;
            default = "/var/lib/postgresql/endoregDbLocal.password";
            description = "Path to file containing endoregDbLocal user password";
          };
        };
      };
	      default = { };
	      description = "Database configuration options";
	    };

      dataRecovery = mkOption {
        type = types.submodule {
          options = {
            enable = mkOption {
              type = types.bool;
              default = true;
              description = "Recover legacy lx-annotate data and media trees into the runtime STORAGE_DIR before boot.";
            };
            legacyDataDir = mkOption {
              type = types.str;
              default = legacyRepoDataRootPath;
              description = "Legacy repo-local data directory to sync from.";
            };
            legacyMediaDir = mkOption {
              type = types.str;
              default = legacyRepoMediaRootPath;
              description = "Legacy media directory to sync from.";
            };
            stateFile = mkOption {
              type = types.str;
              default = dataRecoveryStateFile;
              description = "Stable state file that records the last effective lx-annotate data directory used for migration drift detection.";
            };
          };
        };
        default = { };
        description = "Recovery settings for migrating legacy lx-annotate media into the runtime storage root.";
      };

      dataCleanup = mkOption {
        type = types.submodule {
          options = {
            enable = mkOption {
              type = types.bool;
              default = config.roles.endoreg-client.paths.storagePersistingEnable;
              description = "Regularly move duplicate anonymized lx-annotate payload into external archive storage.";
            };
            legacyDataDir = mkOption {
              type = types.str;
              default = legacyRepoDataRootPath;
              description = "Legacy repo-local data directory to clean up.";
            };
            legacyMediaDir = mkOption {
              type = types.str;
              default = legacyRepoMediaRootPath;
              description = "Legacy media directory to clean up.";
            };
            legacyProcessedReportDir = mkOption {
              type = types.str;
              default = legacyDataProcessedReportDir;
              description = "Legacy processed report directory derived from the lx-annotate service paths.";
            };
            legacyProcessedVideoDir = mkOption {
              type = types.str;
              default = legacyDataProcessedVideoDir;
              description = "Legacy processed video directory derived from the lx-annotate service paths.";
            };
            legacyMediaProcessedReportDir = mkOption {
              type = types.str;
              default = legacyMediaProcessedReportDir;
              description = "Legacy processed report directory under the service media root.";
            };
            legacyMediaProcessedVideoDir = mkOption {
              type = types.str;
              default = legacyMediaProcessedVideoDir;
              description = "Legacy processed video directory under the service media root.";
            };
            archiveDir = mkOption {
              type = types.str;
              default = externalCleanupArchiveRootDefault;
              description = "External archive directory where duplicate files are moved.";
            };
            runtimeProcessedReportDir = mkOption {
              type = types.str;
              default = runtimeProcessedReportDir;
              description = "Runtime processed report directory derived from the lx-annotate service.";
            };
            runtimeProcessedVideoDir = mkOption {
              type = types.str;
              default = runtimeProcessedVideoDir;
              description = "Runtime processed video directory derived from the lx-annotate service.";
            };
            onCalendar = mkOption {
              type = types.str;
              default = "daily";
              description = "systemd timer schedule for duplicate cleanup.";
            };
          };
        };
        default = { };
        description = "Duplicate cleanup settings for anonymized lx-annotate legacy storage.";
      };

      hub = mkOption {
        type = types.submodule {
          options = {
            enable = mkOption {
              type = types.bool;
              default = config.networking.hostName == "gs-02";
              description = "Mark this host as the central lx-annotate hub node and enable central-node groundwork defaults.";
            };
            transferApi = mkOption {
              type = types.submodule {
                options = {
                  enable = mkOption {
                    type = types.bool;
                    default = false;
                    description = "Enable the authenticated node-to-node hub transfer API. Disabled by default even on hub nodes.";
                  };
                  requireSecureTransport = mkOption {
                    type = types.bool;
                    default = true;
                    description = "Require HTTPS-equivalent secure transport for hub transfer requests.";
                  };
                  requireMtls = mkOption {
                    type = types.bool;
                    default = false;
                    description = "Require proxy-verified mutual TLS for node-authenticated hub transfer requests.";
                  };
                  mtlsMetaKey = mkOption {
                    type = types.str;
                    default = "HTTP_X_CLIENT_CERT_VERIFIED";
                    description = "Django request META key used to verify proxy-attested mTLS client authentication.";
                  };
                  mtlsMetaValue = mkOption {
                    type = types.str;
                    default = "SUCCESS";
                    description = "Expected proxy-attested mTLS verification value forwarded to Django.";
                  };
                  clientCaFile = mkOption {
                    type = types.nullOr types.path;
                    default = null;
                    description = "PEM bundle used by Nginx to verify client certificates for hub transfer requests.";
                  };
                };
              };
              default = { };
              description = "Transfer API settings for lx-annotate hub deployments.";
            };
            backup = mkOption {
              type = types.submodule {
                options = {
                  enable = mkOption {
                    type = types.bool;
                    default = false;
                    description = "Enable protected backup groundwork on the hub node. This provisions a landing area for inbound backups and periodic local runtime snapshots.";
                  };
                  incomingDir = mkOption {
                    type = types.str;
                    default = hubBackupIncomingPath;
                    description = "Protected landing directory for inbound backups staged on the hub node.";
                  };
                  snapshotDir = mkOption {
                    type = types.str;
                    default = hubBackupSnapshotPath;
                    description = "Protected directory where the hub node stores timestamped runtime snapshots.";
                  };
                  manifestDir = mkOption {
                    type = types.str;
                    default = hubBackupManifestPath;
                    description = "Protected directory for JSON manifests describing generated hub snapshots.";
                  };
                  sourceRuntimeDir = mkOption {
                    type = types.str;
                    default = runtimeDataRootPath;
                    description = "Runtime tree snapshotted by the hub backup service. This should remain the encrypted lx-annotate data root.";
                  };
                  onCalendar = mkOption {
                    type = types.str;
                    default = "hourly";
                    description = "systemd timer schedule for hub runtime snapshots.";
                  };
                  retainCount = mkOption {
                    type = types.int;
                    default = 48;
                    description = "How many completed snapshots the hub node keeps before pruning older ones.";
                  };
                  exclude = mkOption {
                    type = types.listOf types.str;
                    default = [
                      ".lx-annotate-rsync-partial"
                      "temp"
                      "frames"
                      "raw_frames"
                      "hub/backup/incoming"
                      "hub/backup/snapshots"
                      "hub/backup/manifests"
                    ];
                    description = "Paths excluded from hub runtime snapshots. Defaults omit disposable frame/temp output and the backup directories themselves.";
                  };
                };
              };
              default = { };
              description = "Central hub backup groundwork settings.";
            };
          };
        };
        default = { };
        description = "Central hub groundwork settings for lx-annotate.";
      };
	  };
}
