---
- name: Read postgres user password from vault
  ansible.builtin.slurp:
    src: "{{ lx_vault_dir }}/SCRT_roles_system_password_postgres_host_main_password"
  register: postgres_password_b64
  no_log: true

- name: Set postgres user password
  ansible.builtin.command:
    cmd: psql -U postgres -c "ALTER ROLE postgres WITH PASSWORD '{{ postgres_password_b64.content | b64decode | trim }}';"
  become: true
  become_user: root # Changed from postgres to root
  no_log: false
  register: postgres_password_result
  changed_when: postgres_password_result.rc == 0
  environment:
    PGPASSWORD: "" # Ensure no password is used for peer authentication
    PGHOST: "" # Force local socket connection

- name: Test local postgres connection
  ansible.builtin.command:
    cmd: psql -U postgres -c "SELECT version();"
  become: true
  become_user: root
  register: postgres_test_result
  changed_when: false
  environment:
    PGPASSWORD: ""
    PGHOST: ""
