#!/usr/bin/env python3
"""
lx-secrets — Secrets stick management CLI.

The secrets stick is the root of trust for the LX infrastructure.  It is a
USB device with a well-known directory layout that holds SSH identities,
certificates, and (optionally) user passwords.

Two stick modes:
  admin  — Full network administration: all identities, all certs, can stage
           secrets for Ansible deployment, can import user submissions.
  user   — Personal stick for one user: their SSH key and password only.
           Syncs only public/hashed data to the inventory (no plaintext).

Usage:
    lx-secrets <command> <subcommand> [options]

Commands:
    stick check / init / backup

    identity list
    identity gen-user NAME       Generate a user SSH key-pair on the stick
    identity gen-host NAME       Generate a host SSH key-pair on the stick
    identity import-keypair      Import an existing user key pair (synced to inventory)
    identity import-infra-key    Import an infra key (e.g. Hetzner bootstrap; NOT synced)
    identity sync-inventory      Write pubkeys + password hashes to stick_pubkeys.yml
                                 (safe to commit; no plaintext passwords)

    user set-password       Set or generate a password for a user
    user show-hash          Print the stored password hash (safe)
    user show-password      Print the plaintext password (stick owner only /
                            admin-mode only for other users)
    user sync               Output a YAML snippet for submitting to the admin
                            (personal sticks: own data only)

    admin import-snippet    Import a user's submitted YAML snippet onto the
                            admin stick (pubkey + hash only)
    admin import-pubkey     Import a single pubkey onto the admin stick
    admin list-users        List all users with their data status

    cert list / import-ssl / import-openvpn / deploy-ssl / deploy-openvpn

    vault stage-ssl              Stage SSL cert into ~/.lxv/deploy/<hostname>/
    vault stage-ssl-group        Stage SSL cert for all hosts in an inventory group
    vault stage-keycloak-admin   Stage keycloak_admin bootstrap password for a host
    vault stage-passwords        Write admin-passwords.yml from stick for vault bootstrap
    vault status                 Show staged files per hostname

Stick directory layout (admin mode):
    <stick>/
    ├── .stick-meta.yml                 # mode, uuid, created, version
    ├── identities/
    │   ├── users/
    │   │   └── <username>/
    │   │       ├── id_ed25519[.pub]    # SSH keypair
    │   │       └── secrets/
    │   │           ├── password        # plaintext  (mode 0600, NEVER sync)
    │   │           └── password.hash   # sha512crypt (mode 0644, safe to sync)
    │   ├── infra/
    │   │   └── <name>/
    │   │       └── id_<type>[.pub]     # Infra key (e.g. Hetzner bootstrap; NOT synced)
    │   └── hosts/
    │       └── <hostname>/ssh_host_ed25519_key[.pub]
    ├── certificates/
    │   ├── ssl/<domain>/fullchain.pem + privkey.pem
    │   └── openvpn/
    │       ├── ca/ca.pem + ca.key
    │       ├── server/crt.crt + key.key + dh.pem
    │       ├── tls.pem
    │       └── clients/<hostname>/crt.crt + key.key
    └── backups/<timestamp>.tar.gz

Personal stick layout (user mode):
    <stick>/
    ├── .stick-meta.yml                 # mode: user, owner: <username>
    └── identities/
        └── users/
            └── <owner>/
                ├── id_ed25519[.pub]
                └── secrets/
                    ├── password
                    └── password.hash
"""

from __future__ import annotations

import argparse
import getpass
import os
import secrets as _secrets
import shutil
import stat
import string
import subprocess
import sys
import tarfile
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

STICK_META_FILENAME = ".stick-meta.yml"
STICK_META_VERSION = "1"
ENV_VAR = "LX_SECRETS_STICK"

STICK_LAYOUT_ADMIN = [
    "identities/users",
    "identities/hosts",
    "certificates/openvpn/ca",
    "certificates/openvpn/server",
    "certificates/openvpn/clients",
    "certificates/ssl",
    "backups",
]

STICK_LAYOUT_USER = [
    "identities/users",
    "backups",
]

# Auto-generated by sync-inventory — do not edit by hand
STICK_PUBKEYS_INVENTORY = "ansible/inventory/group_vars/stick_pubkeys.yml"


# ---------------------------------------------------------------------------
# Stick discovery
# ---------------------------------------------------------------------------

def _find_stick() -> Optional[Path]:
    """Locate the secrets stick automatically."""
    env = os.environ.get(ENV_VAR)
    if env:
        p = Path(env)
        if (p / STICK_META_FILENAME).exists():
            return p
        print(
            f"[warn] {ENV_VAR}={env} is set but {STICK_META_FILENAME} was not found there.",
            file=sys.stderr,
        )

    for base in ["/run/media/admin", "/run/media", "/media", "/mnt"]:
        base_path = Path(base)
        if not base_path.is_dir():
            continue
        for candidate in sorted(base_path.iterdir()):
            if candidate.is_dir() and (candidate / STICK_META_FILENAME).exists():
                return candidate

    return None


def require_stick(args) -> Path:
    """Return the stick path or exit with an informative error."""
    if getattr(args, "stick", None):
        p = Path(args.stick)
        if not p.exists():
            print(f"[error] Stick path does not exist: {p}", file=sys.stderr)
            sys.exit(1)
        return p

    p = _find_stick()
    if p is None:
        print(
            f"[error] Secrets stick not found.\n"
            f"  Mount the stick and either:\n"
            f"    export {ENV_VAR}=/path/to/stick\n"
            f"  or pass --stick /path/to/stick",
            file=sys.stderr,
        )
        sys.exit(1)
    return p


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _secure_copy(src: Path, dst: Path, mode: int = stat.S_IRUSR | stat.S_IWUSR) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    os.chmod(dst, mode)


def _read_meta(stick: Path) -> dict:
    return yaml.safe_load((stick / STICK_META_FILENAME).read_text()) or {}


def _write_meta(stick: Path, meta: dict) -> None:
    meta_file = stick / STICK_META_FILENAME
    meta_file.write_text(yaml.dump(meta, default_flow_style=False))
    os.chmod(meta_file, stat.S_IRUSR | stat.S_IWUSR)


def _stick_mode(stick: Path) -> str:
    """Return 'admin' or 'user'."""
    return _read_meta(stick).get("mode", "admin")


def _stick_owner(stick: Path) -> Optional[str]:
    """For user-mode sticks: the username this stick belongs to."""
    return _read_meta(stick).get("owner")


def _require_admin_stick(stick: Path) -> None:
    if _stick_mode(stick) == "user":
        owner = _stick_owner(stick) or "?"
        print(
            f"[error] This is a personal stick (owner: {owner}).\n"
            f"  This command requires an admin stick.",
            file=sys.stderr,
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# Password utilities
# ---------------------------------------------------------------------------

_PASSWORD_ALPHABET = string.ascii_letters + string.digits + "!@#%^&*-_"


def _generate_secure_password(length: int = 24) -> str:
    """Generate a cryptographically random password."""
    return "".join(_secrets.choice(_PASSWORD_ALPHABET) for _ in range(length))


def _hash_password(password: str) -> str:
    """Generate a SHA-512 crypt hash (NixOS hashedPassword format)."""
    result = subprocess.run(
        ["openssl", "passwd", "-6", "-stdin"],
        input=password,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _user_secrets_dir(stick: Path, username: str) -> Path:
    return stick / "identities" / "users" / username / "secrets"


def _get_user_password(stick: Path, username: str) -> Optional[str]:
    p = _user_secrets_dir(stick, username) / "password"
    return p.read_text().strip() if p.exists() else None


def _get_user_hash(stick: Path, username: str) -> Optional[str]:
    p = _user_secrets_dir(stick, username) / "password.hash"
    return p.read_text().strip() if p.exists() else None


def _store_password(stick: Path, username: str, password: str) -> None:
    sdir = _user_secrets_dir(stick, username)
    sdir.mkdir(parents=True, exist_ok=True)

    pwd_file = sdir / "password"
    pwd_file.write_text(password + "\n")
    os.chmod(pwd_file, stat.S_IRUSR | stat.S_IWUSR)  # 0600

    print("[...] Hashing password (sha512crypt)…", file=sys.stderr)
    hashed = _hash_password(password)
    hash_file = sdir / "password.hash"
    hash_file.write_text(hashed + "\n")
    # hash is safe to read by others; 0644
    os.chmod(hash_file, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)


# ---------------------------------------------------------------------------
# stick commands
# ---------------------------------------------------------------------------

def cmd_stick_check(args) -> None:
    stick = require_stick(args)
    meta = _read_meta(stick)
    mode = meta.get("mode", "admin")
    owner = meta.get("owner", "")
    print(f"[ok] Stick found at {stick}")
    print(f"     UUID   : {meta.get('uuid', '?')}")
    print(f"     Mode   : {mode}" + (f"  (owner: {owner})" if owner else ""))
    print(f"     Created: {meta.get('created', '?')}")
    print(f"     Version: {meta.get('version', '?')}")

    layout = STICK_LAYOUT_USER if mode == "user" else STICK_LAYOUT_ADMIN
    missing = [d for d in layout if not (stick / d).is_dir()]
    if missing:
        print(f"[warn] Missing directories: {', '.join(missing)}")
        print(f"       Run 'lx-secrets stick init' to create them.")
    else:
        print("[ok] Directory layout is complete")

    _print_identities(stick)
    if mode == "admin":
        _print_certs(stick)


def cmd_stick_init(args) -> None:
    if getattr(args, "stick", None):
        stick = Path(args.stick)
    else:
        raw = input("Stick mount path: ").strip()
        if not raw:
            print("[error] No path provided.", file=sys.stderr)
            sys.exit(1)
        stick = Path(raw)

    if not stick.exists():
        print(f"[error] Path does not exist: {stick}", file=sys.stderr)
        sys.exit(1)

    if (stick / STICK_META_FILENAME).exists() and not getattr(args, "force", False):
        print(
            f"[error] Stick already initialised at {stick}.\n"
            f"  Pass --force to reinitialise.",
            file=sys.stderr,
        )
        sys.exit(1)

    mode = getattr(args, "mode", "admin") or "admin"
    owner = getattr(args, "owner", None)

    if mode == "user" and not owner:
        print("[error] --owner <username> is required for user-mode sticks.", file=sys.stderr)
        sys.exit(1)

    layout = STICK_LAYOUT_USER if mode == "user" else STICK_LAYOUT_ADMIN
    for d in layout:
        (stick / d).mkdir(parents=True, exist_ok=True)

    meta: dict = {
        "uuid": str(uuid.uuid4()),
        "created": datetime.now().isoformat(),
        "version": STICK_META_VERSION,
        "mode": mode,
    }
    if owner:
        meta["owner"] = owner
        meta["description"] = f"LX personal secrets stick for {owner}"
    else:
        meta["description"] = "LX admin secrets stick"

    _write_meta(stick, meta)
    print(f"[ok] Stick initialised at {stick}  (mode: {mode})")
    if owner:
        print(f"     Owner: {owner}")
    print(f"     UUID : {meta['uuid']}")
    print()
    if mode == "user":
        print(f"Next steps:")
        print(f"  export {ENV_VAR}={stick}")
        print(f"  lx-secrets identity gen-user {owner}")
        print(f"  lx-secrets user set-password --username {owner} --generate")
        print(f"  lx-secrets user sync --output my-pubkey-{owner}.yml")
        print(f"  # Submit my-pubkey-{owner}.yml as a PR for the admin to import")
    else:
        print(f"Next steps:")
        print(f"  export {ENV_VAR}={stick}")
        print(f"  lx-secrets identity gen-user admin")
        print(f"  lx-secrets cert import-openvpn /etc/openvpn")


def cmd_stick_backup(args) -> None:
    stick = require_stick(args)
    backup_dir = stick / "backups"
    backup_dir.mkdir(exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = backup_dir / f"backup_{ts}.tar.gz"

    with tarfile.open(backup_file, "w:gz") as tar:
        for item in sorted(stick.iterdir()):
            if item.name == "backups":
                continue
            tar.add(item, arcname=item.name)

    os.chmod(backup_file, stat.S_IRUSR | stat.S_IWUSR)
    size_kb = backup_file.stat().st_size / 1024
    print(f"[ok] Backup created: {backup_file.name}  ({size_kb:.1f} KB)")

    existing = sorted(backup_dir.glob("backup_*.tar.gz"))
    for old in existing[:-5]:
        old.unlink()
        print(f"[ok] Pruned old backup: {old.name}")


# ---------------------------------------------------------------------------
# identity helpers
# ---------------------------------------------------------------------------

def _user_key_path(stick: Path, username: str, key_type: str) -> Path:
    return stick / "identities" / "users" / username / f"id_{key_type}"


def _host_key_path(stick: Path, hostname: str, key_type: str) -> Path:
    return stick / "identities" / "hosts" / hostname / f"ssh_host_{key_type}_key"


def _generate_keypair(
    private_path: Path, key_type: str, comment: str, force: bool
) -> tuple[Path, Path]:
    pub_path = Path(str(private_path) + ".pub")

    if private_path.exists() and not force:
        raise FileExistsError(
            f"Key already exists: {private_path}\n  Pass --force to overwrite."
        )
    if private_path.exists():
        private_path.unlink()
        pub_path.unlink(missing_ok=True)

    private_path.parent.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(
        ["ssh-keygen", "-t", key_type, "-f", str(private_path), "-N", "", "-C", comment],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)

    os.chmod(private_path, stat.S_IRUSR | stat.S_IWUSR)
    os.chmod(pub_path, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
    return private_path, pub_path


def _print_identities(stick: Path) -> None:
    users_dir = stick / "identities" / "users"
    hosts_dir = stick / "identities" / "hosts"

    if users_dir.is_dir():
        users = sorted(users_dir.iterdir())
        if users:
            print(f"\n  User identities ({len(users)}):")
            for u in users:
                pub = next(u.glob("*.pub"), None)
                has_pwd = (u / "secrets" / "password").exists()
                has_hash = (u / "secrets" / "password.hash").exists()
                key_label = pub.stem.replace("id_", "") if pub else "?"
                short = pub.read_text().strip()[:68] if pub else "(no public key)"
                pwd_tag = " [pwd]" if has_pwd else (" [hash]" if has_hash else "")
                print(f"    {u.name} [{key_label}]{pwd_tag}: {short}…")

    if hosts_dir.is_dir():
        hosts = sorted(hosts_dir.iterdir())
        if hosts:
            print(f"\n  Host identities ({len(hosts)}):")
            for h in hosts:
                pub = next(h.glob("*.pub"), None)
                if pub:
                    short = pub.read_text().strip()[:68]
                    print(f"    {h.name}: {short}…")
                else:
                    print(f"    {h.name}: (no public key)")


# ---------------------------------------------------------------------------
# identity commands
# ---------------------------------------------------------------------------

def cmd_identity_list(args) -> None:
    stick = require_stick(args)
    print(f"Identities on stick at {stick}")
    _print_identities(stick)


def cmd_identity_gen_user(args) -> None:
    stick = require_stick(args)

    # On a user-mode stick: only the owner can generate keys
    mode = _stick_mode(stick)
    owner = _stick_owner(stick)
    if mode == "user" and owner and args.username != owner:
        print(
            f"[error] Personal stick (owner: {owner}) — "
            f"cannot generate keys for '{args.username}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    key_type: str = args.key_type
    username: str = args.username
    priv = _user_key_path(stick, username, key_type)

    try:
        priv, pub = _generate_keypair(priv, key_type, f"{username}@lx-secrets", args.force)
    except FileExistsError as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)

    print(f"[ok] Generated {key_type} key for user '{username}'")
    print(f"     Private : {priv}")
    print(f"     Public  : {pub}")
    print(f"     Pubkey  : {pub.read_text().strip()}")


def cmd_identity_gen_host(args) -> None:
    stick = require_stick(args)
    _require_admin_stick(stick)

    key_type: str = args.key_type
    hostname: str = args.hostname
    priv = _host_key_path(stick, hostname, key_type)

    try:
        priv, pub = _generate_keypair(priv, key_type, f"{hostname}@lx-secrets", args.force)
    except FileExistsError as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)

    print(f"[ok] Generated {key_type} host key for '{hostname}'")
    print(f"     Private : {priv}")
    print(f"     Public  : {pub}")
    print(f"     Pubkey  : {pub.read_text().strip()}")


def cmd_identity_import_keypair(args) -> None:
    """
    Import an existing SSH key pair into the vault.

    Copies both the private key (0600) and public key (0644) into
    <stick>/identities/users/<username>/id_<type>[.pub].

    Use --deploy-local to also install the private key at ~/.ssh/id_<type>.
    """
    stick = require_stick(args)

    username: str = args.username
    priv_src = Path(args.private_key).expanduser()
    pub_src_arg: Optional[str] = getattr(args, "public_key", None)
    pub_src = Path(pub_src_arg).expanduser() if pub_src_arg else None

    if not priv_src.exists():
        print(f"[error] Private key not found: {priv_src}", file=sys.stderr)
        sys.exit(1)

    # Auto-detect public key if not given
    if pub_src is None:
        candidate = Path(str(priv_src) + ".pub")
        if candidate.exists():
            pub_src = candidate
        else:
            print(
                f"[error] Public key not found. Pass --public <path> or place "
                f"<private>.pub alongside the private key.",
                file=sys.stderr,
            )
            sys.exit(1)

    if not pub_src.exists():
        print(f"[error] Public key not found: {pub_src}", file=sys.stderr)
        sys.exit(1)

    # Validate public key format
    pubkey_text = pub_src.read_text().strip()
    parts = pubkey_text.split()
    if len(parts) < 2 or not parts[0].startswith("ssh-"):
        print(f"[error] Invalid public key format in {pub_src}", file=sys.stderr)
        sys.exit(1)
    key_type = parts[0].replace("ssh-", "")  # ed25519, rsa, etc.

    user_dir = stick / "identities" / "users" / username
    priv_dest = user_dir / f"id_{key_type}"
    pub_dest = user_dir / f"id_{key_type}.pub"

    if priv_dest.exists() and not args.force:
        print(
            f"[error] Key already exists at {priv_dest}.\n"
            f"  Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    user_dir.mkdir(parents=True, exist_ok=True)

    _secure_copy(priv_src, priv_dest, stat.S_IRUSR | stat.S_IWUSR)
    _secure_copy(
        pub_src, pub_dest,
        stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH,
    )

    print(f"[ok] Imported {key_type} key pair for '{username}'")
    print(f"     Private : {priv_dest}")
    print(f"     Public  : {pub_dest}")
    print(f"     Pubkey  : {pubkey_text[:80]}{'...' if len(pubkey_text) > 80 else ''}")

    if args.deploy_local:
        local_priv = Path.home() / ".ssh" / f"id_{key_type}"
        if local_priv.exists() and not args.force:
            print(
                f"[warn] {local_priv} already exists — skipping local deploy.\n"
                f"  Use --force to overwrite."
            )
        else:
            _secure_copy(priv_dest, local_priv, stat.S_IRUSR | stat.S_IWUSR)
            print(f"[ok] Deployed private key to {local_priv}")
    else:
        print(f"\nTo deploy the private key locally:")
        print(f"  cp {priv_dest} ~/.ssh/id_{key_type}")
        print(f"  chmod 600 ~/.ssh/id_{key_type}")

    print(f"\nNext: sync public key to Ansible inventory and regenerate NixOS configs:")
    print(f"  python3 scripts/lx-secrets.py identity sync-inventory")
    print(f"  devenv tasks run autoconf:finished")


def cmd_identity_import_infra_key(args) -> None:
    """
    Import an infrastructure SSH key (e.g. Hetzner bootstrap key) into the vault.

    Stored under <stick>/identities/infra/<name>/id_<type>[.pub].
    This path is intentionally separate from identities/users/ so that
    sync-inventory does NOT push this key to stick_pubkeys.yml or any
    machine's authorized_keys.

    Use --deploy-path to install the private key at a custom local path
    (e.g. ~/.ssh/ssh-hetzner-main_openssh) rather than ~/.ssh/id_<type>.
    """
    stick = require_stick(args)

    name: str = args.name
    priv_src = Path(args.private_key).expanduser()
    pub_src_arg: Optional[str] = getattr(args, "public_key", None)
    pub_src = Path(pub_src_arg).expanduser() if pub_src_arg else None
    deploy_path_arg: Optional[str] = getattr(args, "deploy_path", None)

    if not priv_src.exists():
        print(f"[error] Private key not found: {priv_src}", file=sys.stderr)
        sys.exit(1)

    # Auto-detect public key if not given
    if pub_src is None:
        candidate = Path(str(priv_src) + ".pub")
        if candidate.exists():
            pub_src = candidate
        else:
            print(
                f"[error] Public key not found. Pass --public <path> or place "
                f"<private>.pub alongside the private key.",
                file=sys.stderr,
            )
            sys.exit(1)

    if not pub_src.exists():
        print(f"[error] Public key not found: {pub_src}", file=sys.stderr)
        sys.exit(1)

    # Validate public key format
    pubkey_text = pub_src.read_text().strip()
    parts = pubkey_text.split()
    if len(parts) < 2 or not parts[0].startswith("ssh-"):
        print(f"[error] Invalid public key format in {pub_src}", file=sys.stderr)
        sys.exit(1)
    key_type = parts[0].replace("ssh-", "")  # ed25519, rsa, etc.

    infra_dir = stick / "identities" / "infra" / name
    priv_dest = infra_dir / f"id_{key_type}"
    pub_dest = infra_dir / f"id_{key_type}.pub"

    if priv_dest.exists() and not args.force:
        print(
            f"[error] Key already exists at {priv_dest}.\n"
            f"  Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    infra_dir.mkdir(parents=True, exist_ok=True)

    _secure_copy(priv_src, priv_dest, stat.S_IRUSR | stat.S_IWUSR)
    _secure_copy(
        pub_src, pub_dest,
        stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH,
    )

    print(f"[ok] Imported {key_type} infra key '{name}'")
    print(f"     Private : {priv_dest}")
    print(f"     Public  : {pub_dest}")
    print(f"     Pubkey  : {pubkey_text[:80]}{'...' if len(pubkey_text) > 80 else ''}")

    if deploy_path_arg:
        local_priv = Path(deploy_path_arg).expanduser()
        if local_priv.exists() and not args.force:
            print(
                f"[warn] {local_priv} already exists — skipping local deploy.\n"
                f"  Use --force to overwrite."
            )
        else:
            local_priv.parent.mkdir(parents=True, exist_ok=True)
            _secure_copy(priv_dest, local_priv, stat.S_IRUSR | stat.S_IWUSR)
            print(f"[ok] Deployed private key to {local_priv}")
    else:
        print(f"\nTo deploy the private key locally:")
        print(f"  cp {priv_dest} ~/.ssh/id_{key_type}")
        print(f"  chmod 600 ~/.ssh/id_{key_type}")

    print(f"\nNote: this key is stored under identities/infra/ and is NOT synced")
    print(f"to stick_pubkeys.yml or any machine's authorized_keys.")


def cmd_identity_sync_inventory(args) -> None:
    """
    Write public keys AND password hashes from the stick to
    ansible/inventory/group_vars/stick_pubkeys.yml.

    Both pubkeys and SHA-512 hashes are safe to commit to git.
    Plaintext passwords are NEVER written here.

    On a user-mode stick: only the owner's data is written.
    On an admin stick: all users are written.
    """
    stick = require_stick(args)
    out_file = Path(args.output)
    mode = _stick_mode(stick)
    owner = _stick_owner(stick)

    authentication: dict = {}

    users_dir = stick / "identities" / "users"
    if users_dir.is_dir():
        for user_dir in sorted(users_dir.iterdir()):
            if not user_dir.is_dir():
                continue
            username = user_dir.name

            # User-mode stick: only emit own data
            if mode == "user" and owner and username != owner:
                continue

            entry: dict = {}
            for pub_file in sorted(user_dir.glob("*.pub")):
                key_name = pub_file.stem  # e.g. id_ed25519
                entry[f"{key_name}_pub"] = pub_file.read_text().strip()

            hash_val = _get_user_hash(stick, username)
            if hash_val and not getattr(args, "no_hashes", False):
                entry["password_hash"] = hash_val

            if entry:
                authentication[username] = entry

    if not authentication:
        print("[warn] No user data found on stick — nothing to sync.")
        return

    output = (
        "# AUTO-GENERATED by: lx-secrets identity sync-inventory\n"
        "# DO NOT EDIT — regenerate with: devenv tasks run secrets:sync-inventory\n"
        "---\n"
    )
    output += yaml.dump(
        {"authentication": authentication},
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=True,
        width=4096,
    )

    if getattr(args, "dry_run", False):
        print("[dry-run] Would write:")
        print(output)
        return

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(output)
    print(f"[ok] Wrote {len(authentication)} identities to {out_file}")
    for name, entry in sorted(authentication.items()):
        tags = []
        for k in entry:
            if k.endswith("_pub"):
                tags.append(k)
            elif k == "password_hash":
                tags.append("hash")
        print(f"     {name}: {', '.join(tags)}")


# ---------------------------------------------------------------------------
# user commands  (personal stick operations)
# ---------------------------------------------------------------------------

def _resolve_user_username(stick: Path, args) -> str:
    """Return the username to operate on, enforcing ownership for user-mode sticks."""
    mode = _stick_mode(stick)
    owner = _stick_owner(stick)
    username = getattr(args, "username", None) or owner

    if not username:
        print(
            "[error] Could not determine username.  "
            "Pass --username or use a personal stick with --owner set.",
            file=sys.stderr,
        )
        sys.exit(1)

    if mode == "user" and owner and username != owner:
        print(
            f"[error] Personal stick (owner: {owner}) — "
            f"cannot operate on user '{username}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    return username


def cmd_user_set_password(args) -> None:
    """
    Set or generate a password for a user and store it on the stick.

    --generate creates a random 24-character password and prints it once.
    Without --generate, you are prompted for the password interactively.

    The plaintext is stored at mode 0600.  The sha512crypt hash is stored
    at mode 0644 and is safe to sync to the Ansible inventory.
    """
    stick = require_stick(args)
    username = _resolve_user_username(stick, args)

    if getattr(args, "generate", False):
        password = _generate_secure_password()
        print(f"[ok] Generated password for '{username}':")
        print(f"     {password}")
        print(f"     (shown once — save it now)")
    else:
        password = getpass.getpass(f"Password for {username}: ")
        confirm = getpass.getpass("Confirm password: ")
        if password != confirm:
            print("[error] Passwords do not match.", file=sys.stderr)
            sys.exit(1)

    _store_password(stick, username, password)
    hash_val = _get_user_hash(stick, username) or ""
    print(f"[ok] Password stored for '{username}'")
    print(f"     Hash (first 20 chars): {hash_val[:20]}…")
    print(f"\nSync to inventory:")
    print(f"  lx-secrets identity sync-inventory")


def cmd_user_show_hash(args) -> None:
    """Print the sha512crypt hash for a user — safe to share and commit."""
    stick = require_stick(args)
    username = _resolve_user_username(stick, args)
    h = _get_user_hash(stick, username)
    if not h:
        print(f"[error] No password hash for '{username}'. Run 'user set-password' first.",
              file=sys.stderr)
        sys.exit(1)
    print(h)


def cmd_user_show_password(args) -> None:
    """
    Print the plaintext password.

    On a user-mode stick: only available for the stick's own owner.
    On an admin stick: available for all users (requires --confirm flag).
    """
    stick = require_stick(args)
    mode = _stick_mode(stick)
    owner = _stick_owner(stick)
    username = _resolve_user_username(stick, args)

    if mode == "admin" and not getattr(args, "confirm", False):
        print(
            "[error] Showing plaintext passwords from an admin stick requires --confirm.",
            file=sys.stderr,
        )
        sys.exit(1)

    pwd = _get_user_password(stick, username)
    if not pwd:
        print(f"[error] No stored password for '{username}'.", file=sys.stderr)
        sys.exit(1)
    print(pwd)


def cmd_user_sync(args) -> None:
    """
    Output a YAML snippet with this user's pubkey and password hash.

    This is the safe submission format: no plaintext passwords.
    Users on personal sticks run this and submit the output as a PR.
    Admins use 'admin import-snippet' to bring it onto the admin stick.
    """
    stick = require_stick(args)
    username = _resolve_user_username(stick, args)

    entry: dict = {}
    user_dir = stick / "identities" / "users" / username
    for pub_file in sorted(user_dir.glob("*.pub")):
        entry[f"{pub_file.stem}_pub"] = pub_file.read_text().strip()

    h = _get_user_hash(stick, username)
    if h:
        entry["password_hash"] = h

    if not entry:
        print(f"[error] No data for user '{username}' on stick.", file=sys.stderr)
        sys.exit(1)

    doc = {
        "# Submitted by": username,
        "# Generated": datetime.now().isoformat(),
    }
    output = (
        f"# User sync submission for: {username}\n"
        f"# Generated: {datetime.now().isoformat()}\n"
        f"# Submit this file as a PR; the admin will import it with:\n"
        f"#   lx-secrets admin import-snippet <this-file>\n"
        "---\n"
    )
    output += yaml.dump(
        {"authentication": {username: entry}},
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=True,
        width=4096,
    )

    out_path = getattr(args, "output", None)
    if out_path:
        Path(out_path).write_text(output)
        print(f"[ok] Wrote submission to {out_path}")
    else:
        print(output)


# ---------------------------------------------------------------------------
# admin commands
# ---------------------------------------------------------------------------

def cmd_admin_import_snippet(args) -> None:
    """
    Import a user's submitted YAML snippet onto the admin stick.

    The snippet format is the output of 'user sync': an 'authentication'
    dict with pubkeys and password hashes.  Plaintext passwords are not
    accepted here — they would be rejected.

    Only the pubkey and password_hash fields are imported.
    """
    stick = require_stick(args)
    _require_admin_stick(stick)

    snippet_path = Path(args.snippet_file)
    if not snippet_path.exists():
        print(f"[error] Snippet file not found: {snippet_path}", file=sys.stderr)
        sys.exit(1)

    data = yaml.safe_load(snippet_path.read_text()) or {}
    auth = data.get("authentication", {})
    if not auth:
        print("[error] No 'authentication' key found in snippet.", file=sys.stderr)
        sys.exit(1)

    imported = 0
    for username, entry in auth.items():
        if not isinstance(entry, dict):
            continue

        user_dir = stick / "identities" / "users" / username
        user_dir.mkdir(parents=True, exist_ok=True)

        # Import pubkeys
        for field, value in entry.items():
            if field.endswith("_pub"):
                key_name = field[:-4]  # strip _pub → id_ed25519
                pub_file = user_dir / f"{key_name}.pub"
                pub_file.write_text(value.strip() + "\n")
                os.chmod(pub_file, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
                print(f"[ok] {username}: imported {field}")
                imported += 1
            elif field == "password_hash":
                sdir = _user_secrets_dir(stick, username)
                sdir.mkdir(parents=True, exist_ok=True)
                hash_file = sdir / "password.hash"
                hash_file.write_text(value.strip() + "\n")
                os.chmod(hash_file, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
                print(f"[ok] {username}: imported password_hash")
                imported += 1
            elif field == "password":
                print(f"[skip] {username}: plaintext 'password' field rejected — import denied")

    if imported:
        print(f"\n[ok] Imported {imported} fields. Run 'identity sync-inventory' to update inventory.")
    else:
        print("[warn] Nothing was imported.")


def cmd_admin_import_pubkey(args) -> None:
    """Import a single public key for a user onto the admin stick."""
    stick = require_stick(args)
    _require_admin_stick(stick)

    username: str = args.username
    pubkey: str = args.pubkey.strip()

    # Validate pubkey format roughly
    parts = pubkey.split()
    if len(parts) < 2 or not parts[0].startswith("ssh-"):
        print("[error] Pubkey must be in 'ssh-<type> <base64>' format.", file=sys.stderr)
        sys.exit(1)

    key_type = parts[0].replace("ssh-", "")  # ed25519, rsa, etc.
    user_dir = stick / "identities" / "users" / username
    user_dir.mkdir(parents=True, exist_ok=True)

    pub_file = user_dir / f"id_{key_type}.pub"
    pub_file.write_text(pubkey + "\n")
    os.chmod(pub_file, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
    print(f"[ok] Imported id_{key_type}.pub for '{username}'")
    print(f"     {pubkey[:72]}…")


def cmd_admin_list_users(args) -> None:
    """List all users on the admin stick with their data status."""
    stick = require_stick(args)
    _require_admin_stick(stick)

    users_dir = stick / "identities" / "users"
    if not users_dir.is_dir() or not any(users_dir.iterdir()):
        print("[info] No user identities on stick.")
        return

    print(f"{'User':<20} {'Key':<10} {'Hash':<8} {'Pwd':<6}")
    print("-" * 48)
    for user_dir in sorted(users_dir.iterdir()):
        if not user_dir.is_dir():
            continue
        username = user_dir.name
        pub = next(user_dir.glob("*.pub"), None)
        key_label = pub.stem.replace("id_", "") if pub else "—"
        has_hash = "yes" if _get_user_hash(stick, username) else "—"
        has_pwd = "yes" if _get_user_password(stick, username) else "—"
        print(f"{username:<20} {key_label:<10} {has_hash:<8} {has_pwd:<6}")


# ---------------------------------------------------------------------------
# cert helpers
# ---------------------------------------------------------------------------

def _print_certs(stick: Path) -> None:
    ssl_dir = stick / "certificates" / "ssl"
    vpn_dir = stick / "certificates" / "openvpn"

    if ssl_dir.is_dir():
        domains = sorted(ssl_dir.iterdir())
        if domains:
            print(f"\n  SSL certificates ({len(domains)}):")
            for d in domains:
                has_cert = "[cert]" if (d / "fullchain.pem").exists() else "[NO CERT]"
                has_key = "[key]" if (d / "privkey.pem").exists() else "[NO KEY]"
                print(f"    {d.name}: {has_cert} {has_key}")

    if vpn_dir.is_dir():
        checks = {
            "CA cert":    vpn_dir / "ca" / "ca.pem",
            "CA key":     vpn_dir / "ca" / "ca.key",
            "Server crt": vpn_dir / "server" / "crt.crt",
            "Server key": vpn_dir / "server" / "key.key",
            "DH params":  vpn_dir / "server" / "dh.pem",
            "TLS auth":   vpn_dir / "tls.pem",
        }
        clients_dir = vpn_dir / "clients"
        clients = sorted(clients_dir.iterdir()) if clients_dir.is_dir() else []

        print(f"\n  OpenVPN:")
        for label, path in checks.items():
            status = "[ok]" if path.exists() else "[missing]"
            print(f"    {label:<12}: {status}")
        if clients:
            names = ", ".join(c.name for c in clients)
            print(f"    Clients     : {names}")


# ---------------------------------------------------------------------------
# cert commands
# ---------------------------------------------------------------------------

def cmd_cert_list(args) -> None:
    stick = require_stick(args)
    print(f"Certificates on stick at {stick}")
    _print_certs(stick)


def cmd_cert_import_ssl(args) -> None:
    stick = require_stick(args)
    _require_admin_stick(stick)
    domain: str = args.domain
    cert_src = Path(args.cert)
    key_src = Path(args.key)

    for p, label in [(cert_src, "Certificate"), (key_src, "Key")]:
        if not p.exists():
            print(f"[error] {label} file not found: {p}", file=sys.stderr)
            sys.exit(1)

    dest = stick / "certificates" / "ssl" / domain
    dest.mkdir(parents=True, exist_ok=True)

    _secure_copy(cert_src, dest / "fullchain.pem", stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP)
    _secure_copy(key_src, dest / "privkey.pem", stat.S_IRUSR | stat.S_IWUSR)

    print(f"[ok] Imported SSL certificate for '{domain}'")
    print(f"     Cert : {dest / 'fullchain.pem'}")
    print(f"     Key  : {dest / 'privkey.pem'}")


def cmd_cert_import_openvpn(args) -> None:
    stick = require_stick(args)
    _require_admin_stick(stick)
    src = Path(args.src_dir)
    if not src.is_dir():
        print(f"[error] Source directory not found: {src}", file=sys.stderr)
        sys.exit(1)

    vpn_dir = stick / "certificates" / "openvpn"

    file_mappings: list[tuple[Path, Path]] = [
        (src / "ca.pem",  vpn_dir / "ca" / "ca.pem"),
        (src / "ca.key",  vpn_dir / "ca" / "ca.key"),
        (src / "crt.crt", vpn_dir / "server" / "crt.crt"),
        (src / "key.key", vpn_dir / "server" / "key.key"),
        (src / "dh.pem",  vpn_dir / "server" / "dh.pem"),
        (src / "tls.pem", vpn_dir / "tls.pem"),
    ]

    for src_file, dst_file in file_mappings:
        if src_file.exists():
            _secure_copy(src_file, dst_file)
            print(f"[ok]   {src_file.name} -> {dst_file}")
        else:
            print(f"[skip] {src_file.name} not found in {src}")

    ccd_src = src / "ccd"
    if ccd_src.is_dir():
        shutil.copytree(ccd_src, vpn_dir / "ccd", dirs_exist_ok=True)
        print(f"[ok]   ccd/ -> {vpn_dir / 'ccd'}")

    clients_src = src / "clients"
    if clients_src.is_dir():
        for client_dir in sorted(clients_src.iterdir()):
            if not client_dir.is_dir():
                continue
            client_dst = vpn_dir / "clients" / client_dir.name
            client_dst.mkdir(parents=True, exist_ok=True)
            for f in client_dir.iterdir():
                _secure_copy(f, client_dst / f.name)
            print(f"[ok]   client/{client_dir.name} -> {client_dst}")


def cmd_cert_deploy_ssl(args) -> None:
    stick = require_stick(args)
    domain: str = args.domain
    dest_dir = Path(args.dest).expanduser()

    cert_src = stick / "certificates" / "ssl" / domain / "fullchain.pem"
    key_src = stick / "certificates" / "ssl" / domain / "privkey.pem"

    if not cert_src.exists():
        print(
            f"[error] No SSL certificate for domain '{domain}' on stick.\n"
            f"  Run: lx-secrets cert import-ssl {domain} <cert> <key>",
            file=sys.stderr,
        )
        sys.exit(1)

    dest_dir.mkdir(parents=True, exist_ok=True)
    _secure_copy(cert_src, dest_dir / "ssl_cert", stat.S_IRUSR | stat.S_IWUSR)
    _secure_copy(key_src, dest_dir / "ssl_key", stat.S_IRUSR | stat.S_IWUSR)

    print(f"[ok] Deployed SSL cert for '{domain}' to {dest_dir}")


def cmd_cert_deploy_openvpn(args) -> None:
    stick = require_stick(args)
    dest_dir = Path(args.dest)
    dest_dir.mkdir(parents=True, exist_ok=True)

    vpn_dir = stick / "certificates" / "openvpn"
    file_mappings: list[tuple[Path, Path]] = [
        (vpn_dir / "ca" / "ca.pem",      dest_dir / "ca.pem"),
        (vpn_dir / "server" / "crt.crt", dest_dir / "crt.crt"),
        (vpn_dir / "server" / "key.key", dest_dir / "key.key"),
        (vpn_dir / "server" / "dh.pem",  dest_dir / "dh.pem"),
        (vpn_dir / "tls.pem",            dest_dir / "tls.pem"),
    ]

    for src_file, dst_file in file_mappings:
        if src_file.exists():
            _secure_copy(src_file, dst_file)
            print(f"[ok]   {src_file.name} -> {dst_file}")
        else:
            print(f"[skip] {src_file.name} not on stick")

    ccd_src = vpn_dir / "ccd"
    if ccd_src.is_dir():
        shutil.copytree(ccd_src, dest_dir / "ccd", dirs_exist_ok=True)
        print(f"[ok]   ccd/ -> {dest_dir / 'ccd'}")


# ---------------------------------------------------------------------------
# vault helpers
# ---------------------------------------------------------------------------

def _parse_inventory_group(hosts_ini: Path, group: str) -> list[str]:
    """Return hostnames in a given group from a plain INI-format inventory."""
    hostnames: list[str] = []
    in_group = False
    with hosts_ini.open() as fh:
        for raw_line in fh:
            line = raw_line.strip()
            if line == f"[{group}]":
                in_group = True
                continue
            if in_group:
                if line.startswith("["):
                    break
                if line and not line.startswith(";") and not line.startswith("#"):
                    hostnames.append(line.split()[0])
    return hostnames


def _stage_ssl_for_host(stick: Path, domain: str, hostname: str, vault_dir: Path) -> None:
    cert_src = stick / "certificates" / "ssl" / domain / "fullchain.pem"
    key_src = stick / "certificates" / "ssl" / domain / "privkey.pem"

    if not cert_src.exists():
        print(
            f"[error] No SSL cert for domain '{domain}' on stick.\n"
            f"  Run: lx-secrets cert import-ssl {domain} <cert_pem> <key_pem>",
            file=sys.stderr,
        )
        sys.exit(1)

    deploy_dir = vault_dir / "deploy" / hostname
    deploy_dir.mkdir(parents=True, exist_ok=True)

    _secure_copy(cert_src, deploy_dir / "ssl_cert", stat.S_IRUSR | stat.S_IWUSR)
    _secure_copy(key_src, deploy_dir / "ssl_key", stat.S_IRUSR | stat.S_IWUSR)
    print(f"[ok] {hostname}: ssl_cert + ssl_key staged in {deploy_dir}")


# ---------------------------------------------------------------------------
# vault commands
# ---------------------------------------------------------------------------

def cmd_vault_stage_ssl(args) -> None:
    stick = require_stick(args)
    _require_admin_stick(stick)
    domain: str = args.domain
    hostname: str = args.hostname
    vault_dir = Path(args.vault_dir).expanduser()

    _stage_ssl_for_host(stick, domain, hostname, vault_dir)
    print(f"\nDeploy to host with:")
    print(f"  ansible-playbook ansible/playbooks/deploy_secrets.yml --limit {hostname}")


def cmd_vault_stage_ssl_group(args) -> None:
    stick = require_stick(args)
    _require_admin_stick(stick)
    domain: str = args.domain
    group: str = args.group
    vault_dir = Path(args.vault_dir).expanduser()
    hosts_ini = Path(args.hosts_ini)

    if not hosts_ini.exists():
        print(f"[error] Inventory file not found: {hosts_ini}", file=sys.stderr)
        sys.exit(1)

    hostnames = _parse_inventory_group(hosts_ini, group)
    if not hostnames:
        print(f"[warn] No hosts found in group '[{group}]' in {hosts_ini}")
        return

    print(f"Staging SSL cert for {len(hostnames)} hosts in [{group}]:")
    for hostname in hostnames:
        _stage_ssl_for_host(stick, domain, hostname, vault_dir)

    print(f"\nDeploy to all hosts in group with:")
    print(f"  ansible-playbook ansible/playbooks/deploy_secrets.yml --limit {group}")


def cmd_vault_stage_passwords(args) -> None:
    """
    Read plaintext passwords from the stick and write a YAML file in the
    format expected by bootstrap-lx-vault.py --admin-passwords.

    This is an ADMIN-ONLY operation.  The output file contains plaintext
    passwords and must be handled with care (delete after use).

    The file can be fed to the vault bootstrapper:
        uv run python scripts/bootstrap-lx-vault.py \\
            --admin-passwords <output-file> --export
    """
    stick = require_stick(args)
    _require_admin_stick(stick)

    out_file = Path(args.output).expanduser()
    username_filter: Optional[str] = getattr(args, "username", None)

    users_dir = stick / "identities" / "users"
    if not users_dir.is_dir():
        print("[warn] No user identities on stick.")
        return

    passwords: dict = {}
    for user_dir in sorted(users_dir.iterdir()):
        if not user_dir.is_dir():
            continue
        username = user_dir.name
        if username_filter and username != username_filter:
            continue
        pwd = _get_user_password(stick, username)
        if pwd:
            passwords[username] = pwd
        else:
            print(f"[skip] {username}: no plaintext password on stick")

    if not passwords:
        print("[warn] No passwords found to stage.")
        return

    output = (
        "# AUTO-GENERATED by lx-secrets vault stage-passwords\n"
        "# CONTAINS PLAINTEXT PASSWORDS — handle with care, delete after use\n"
        "---\n"
    )
    output += yaml.dump(
        {"admin_passwords": passwords},
        default_flow_style=False,
        allow_unicode=True,
        width=4096,
    )

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(output)
    os.chmod(out_file, stat.S_IRUSR | stat.S_IWUSR)
    print(f"[ok] Staged {len(passwords)} passwords to {out_file}")
    print(f"\nFeed to vault bootstrapper:")
    print(f"  uv run python scripts/bootstrap-lx-vault.py \\")
    print(f"    --admin-passwords {out_file} --export")
    print(f"\n[!] Delete this file after use:")
    print(f"  shred -u {out_file}")


def cmd_vault_stage_keycloak_admin(args) -> None:
    """
    Read the 'keycloak_admin' password from the stick and stage it as a
    vault-encrypted secret for the target host.

    The staged file is:
      ~/.lxv/deploy/<hostname>/SCRT_roles_system_password_keycloak_host_admin_initial_password

    It is encrypted with ansible-vault using the host's PSK so it can be
    deployed via deploy_secrets.yml just like any other vault secret.

    The NixOS keycloakHost module reads this file at runtime via
    keycloak-prepare-admin-env.service — the plaintext never enters the Nix
    store.

    Prerequisites:
      1.  The 'keycloak_admin' user entry must exist on the stick:
            lx-secrets user set-password keycloak_admin --generate
      2.  The target host's PSK must exist at:
            ~/.lxv/psk/<hostname>.psk
    """
    stick = require_stick(args)
    _require_admin_stick(stick)
    hostname: str = args.hostname
    vault_dir = Path(args.vault_dir).expanduser()

    psk_file = vault_dir / "psk" / f"{hostname}.psk"
    if not psk_file.exists():
        print(
            f"[error] PSK not found for host '{hostname}': {psk_file}\n"
            f"  Run the vault bootstrap to generate PSKs first.",
            file=sys.stderr,
        )
        sys.exit(1)

    password = _get_user_password(stick, "keycloak_admin")
    if not password:
        print(
            "[error] No 'keycloak_admin' password found on stick.\n"
            "  Create one with:\n"
            "    lx-secrets user set-password --username keycloak_admin --generate",
            file=sys.stderr,
        )
        sys.exit(1)

    secret_name = "SCRT_roles_system_password_keycloak_host_admin_initial_password"
    deploy_dir = vault_dir / "deploy" / hostname
    deploy_dir.mkdir(parents=True, exist_ok=True)
    out_file = deploy_dir / secret_name

    # Write plaintext, then encrypt in-place with the host's vault-id label.
    # The label is already registered in ansible.cfg's vault_identity_list with
    # its PSK file, so ansible-vault resolves the password from there.
    out_file.write_text(password)
    os.chmod(out_file, stat.S_IRUSR | stat.S_IWUSR)

    # ansible.cfg has vault_identity_list = h-01@/path/h-01.psk, ...
    # --encrypt-vault-id matches against configured labels only (no @file suffix).
    # Passing the label alone lets ansible-vault look up its PSK from the config.
    result = subprocess.run(
        [
            "ansible-vault", "encrypt",
            f"--encrypt-vault-id={hostname}",
            str(out_file),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        out_file.unlink(missing_ok=True)
        print(f"[error] ansible-vault encrypt failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(result.returncode)

    print(f"[ok] Staged {secret_name} for {hostname} (vault-encrypted with PSK)")
    print(f"     Deploy with:")
    print(f"       ansible-playbook ansible/playbooks/deploy_secrets.yml --limit {hostname}")


def cmd_vault_status(args) -> None:
    vault_dir = Path(args.vault_dir).expanduser()
    deploy_dir = vault_dir / "deploy"

    if not deploy_dir.is_dir():
        print(f"[info] No deploy directory at {deploy_dir}")
        return

    hostname_filter: Optional[str] = getattr(args, "hostname", None)
    entries = sorted(deploy_dir.iterdir())

    if not entries:
        print("[info] No staged secrets found.")
        return

    print(f"Staged secrets in {deploy_dir}:")
    for host_dir in entries:
        if not host_dir.is_dir():
            continue
        if hostname_filter and host_dir.name != hostname_filter:
            continue
        files = sorted(f.name for f in host_dir.iterdir() if f.is_file())
        print(f"\n  {host_dir.name} ({len(files)} files):")
        for fname in files:
            fpath = host_dir / fname
            size = fpath.stat().st_size
            perms = oct(stat.S_IMODE(fpath.stat().st_mode))
            try:
                is_vault = fpath.read_bytes()[:14] == b"$ANSIBLE_VAULT"
            except Exception:
                is_vault = False
            tag = "[vault-encrypted]" if is_vault else "[plaintext]"
            print(f"    {fname:<45} {size:>6} B  {perms}  {tag}")


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(
        prog="lx-secrets",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    root.add_argument(
        "--stick",
        metavar="PATH",
        help=f"Override stick path (also set via {ENV_VAR})",
    )

    sub = root.add_subparsers(dest="command", metavar="COMMAND", required=True)

    # ---- stick ----
    stick_cmd = sub.add_parser("stick", help="Stick lifecycle operations")
    stick_sub = stick_cmd.add_subparsers(dest="subcommand", metavar="SUBCOMMAND", required=True)

    stick_sub.add_parser("check", help="Verify stick is present and valid")

    init_p = stick_sub.add_parser("init", help="Initialise directory layout on a new stick")
    init_p.add_argument("--force", action="store_true", help="Reinitialise even if already set up")
    init_p.add_argument(
        "--mode", choices=["admin", "user"], default="admin",
        help="Stick mode: 'admin' for full network management, 'user' for personal use (default: admin)"
    )
    init_p.add_argument(
        "--owner", metavar="USERNAME",
        help="Username for user-mode sticks (required when --mode user)"
    )

    stick_sub.add_parser("backup", help="Create a backup archive on the stick")

    # ---- identity ----
    id_cmd = sub.add_parser("identity", help="SSH identity management")
    id_sub = id_cmd.add_subparsers(dest="subcommand", metavar="SUBCOMMAND", required=True)

    id_sub.add_parser("list", help="List all identities on the stick")

    gen_user = id_sub.add_parser("gen-user", help="Generate a user SSH key-pair")
    gen_user.add_argument("username", help="Username")
    gen_user.add_argument(
        "--key-type", dest="key_type", default="ed25519",
        choices=["ed25519", "rsa"], help="Key algorithm (default: ed25519)"
    )
    gen_user.add_argument("--force", action="store_true", help="Overwrite existing key")

    gen_host = id_sub.add_parser("gen-host", help="Generate a host SSH key-pair (admin only)")
    gen_host.add_argument("hostname", help="Hostname")
    gen_host.add_argument(
        "--key-type", dest="key_type", default="ed25519",
        choices=["ed25519", "rsa"], help="Key algorithm (default: ed25519)"
    )
    gen_host.add_argument("--force", action="store_true", help="Overwrite existing key")

    imp_kp = id_sub.add_parser(
        "import-keypair",
        help="Import an existing SSH key pair into the vault",
    )
    imp_kp.add_argument("username", help="Username to import under (e.g. admin, dev_01)")
    imp_kp.add_argument(
        "--private", dest="private_key", required=True, metavar="FILE",
        help="Path to the private key file",
    )
    imp_kp.add_argument(
        "--public", dest="public_key", default=None, metavar="FILE",
        help="Path to the public key file (default: <private>.pub)",
    )
    imp_kp.add_argument(
        "--force", action="store_true",
        help="Overwrite existing key in vault (and local ~/.ssh/ if --deploy-local)",
    )
    imp_kp.add_argument(
        "--deploy-local", action="store_true",
        help="Also install the private key to ~/.ssh/id_<type> on this machine",
    )

    imp_infra = id_sub.add_parser(
        "import-infra-key",
        help="Import an infrastructure SSH key (stored under identities/infra/, NOT synced to inventory)",
    )
    imp_infra.add_argument("name", help="Identifier for the key (e.g. hetzner-main)")
    imp_infra.add_argument(
        "--private", dest="private_key", required=True, metavar="FILE",
        help="Path to the private key file",
    )
    imp_infra.add_argument(
        "--public", dest="public_key", default=None, metavar="FILE",
        help="Path to the public key file (default: <private>.pub)",
    )
    imp_infra.add_argument(
        "--force", action="store_true",
        help="Overwrite existing key in vault and local deploy target",
    )
    imp_infra.add_argument(
        "--deploy-path", dest="deploy_path", default=None, metavar="PATH",
        help="Install the private key at this local path (e.g. ~/.ssh/ssh-hetzner-main_openssh)",
    )

    sync_p = id_sub.add_parser(
        "sync-inventory",
        help="Write pubkeys + password hashes to ansible/inventory/group_vars/stick_pubkeys.yml",
    )
    sync_p.add_argument(
        "--output", default=STICK_PUBKEYS_INVENTORY, metavar="FILE",
        help=f"Output file (default: {STICK_PUBKEYS_INVENTORY})",
    )
    sync_p.add_argument("--no-hashes", action="store_true", help="Omit password hashes from output")
    sync_p.add_argument("--dry-run", action="store_true", help="Print output without writing")

    # ---- user ----
    user_cmd = sub.add_parser(
        "user",
        help="Personal password & identity management (works on both stick modes)",
    )
    user_sub = user_cmd.add_subparsers(dest="subcommand", metavar="SUBCOMMAND", required=True)

    _u_arg = dict(metavar="USERNAME", dest="username", default=None,
                  help="Username (inferred from personal stick owner if omitted)")

    set_pwd = user_sub.add_parser("set-password", help="Set or generate a user password on the stick")
    set_pwd.add_argument("--username", **_u_arg)
    set_pwd.add_argument(
        "--generate", action="store_true",
        help="Generate a random 24-character password instead of prompting"
    )

    show_hash = user_sub.add_parser("show-hash", help="Print the sha512crypt hash (safe to share)")
    show_hash.add_argument("--username", **_u_arg)

    show_pwd = user_sub.add_parser("show-password", help="Print the plaintext password")
    show_pwd.add_argument("--username", **_u_arg)
    show_pwd.add_argument(
        "--confirm", action="store_true",
        help="Required on admin sticks to prevent accidental exposure"
    )

    user_sync = user_sub.add_parser(
        "sync",
        help="Output a YAML snippet (pubkey + hash) for submitting to the admin",
    )
    user_sync.add_argument("--username", **_u_arg)
    user_sync.add_argument(
        "--output", metavar="FILE", default=None,
        help="Write to FILE instead of stdout"
    )

    # ---- admin ----
    admin_cmd = sub.add_parser(
        "admin",
        help="Admin-only operations: import user submissions, manage all users",
    )
    admin_sub = admin_cmd.add_subparsers(dest="subcommand", metavar="SUBCOMMAND", required=True)

    imp_snip = admin_sub.add_parser(
        "import-snippet",
        help="Import a user's submitted YAML snippet (pubkey + hash; no plaintext passwords)",
    )
    imp_snip.add_argument("snippet_file", metavar="SNIPPET_YML", help="Path to the snippet file")

    imp_pub = admin_sub.add_parser("import-pubkey", help="Import a single pubkey for a user")
    imp_pub.add_argument("username", help="Username")
    imp_pub.add_argument("pubkey", help="SSH public key string (e.g. 'ssh-ed25519 AAAA…')")

    admin_sub.add_parser("list-users", help="List all users with their data status")

    # ---- cert ----
    cert_cmd = sub.add_parser("cert", help="Certificate management (admin only)")
    cert_sub = cert_cmd.add_subparsers(dest="subcommand", metavar="SUBCOMMAND", required=True)

    cert_sub.add_parser("list", help="List certificates on the stick")

    imp_ssl = cert_sub.add_parser("import-ssl", help="Import an SSL/TLS certificate")
    imp_ssl.add_argument("domain", help="Domain name (e.g. endo-reg.net)")
    imp_ssl.add_argument("cert", metavar="CERT_PEM", help="Path to fullchain/certificate PEM")
    imp_ssl.add_argument("key", metavar="KEY_PEM", help="Path to private key PEM")

    imp_vpn = cert_sub.add_parser("import-openvpn", help="Import OpenVPN certificate material")
    imp_vpn.add_argument(
        "src_dir", metavar="SRC_DIR",
        help="Directory with ca.pem, crt.crt, key.key, dh.pem, tls.pem (e.g. /etc/openvpn)",
    )

    dep_ssl = cert_sub.add_parser("deploy-ssl", help="Copy SSL cert to a staging directory")
    dep_ssl.add_argument("domain", help="Domain name")
    dep_ssl.add_argument("--dest", default="~/.lxv/deploy/ssl", metavar="DIR")

    dep_vpn = cert_sub.add_parser("deploy-openvpn", help="Copy OpenVPN certs to target directory")
    dep_vpn.add_argument("--dest", default="/etc/openvpn", metavar="DIR")

    # ---- vault ----
    vault_cmd = sub.add_parser(
        "vault",
        help="Integrate stick secrets with the Luxnix vault (~/.lxv/deploy/)",
    )
    vault_sub = vault_cmd.add_subparsers(dest="subcommand", metavar="SUBCOMMAND", required=True)

    _vault_dir_arg = dict(
        metavar="DIR", default="~/.lxv", dest="vault_dir",
        help="Vault root directory (default: ~/.lxv)",
    )

    stage_ssl = vault_sub.add_parser(
        "stage-ssl", help="Stage SSL cert from stick into ~/.lxv/deploy/<hostname>/",
    )
    stage_ssl.add_argument("domain")
    stage_ssl.add_argument("hostname")
    stage_ssl.add_argument("--vault-dir", **_vault_dir_arg)

    stage_ssl_grp = vault_sub.add_parser(
        "stage-ssl-group", help="Stage SSL cert for all hosts in an inventory group",
    )
    stage_ssl_grp.add_argument("domain")
    stage_ssl_grp.add_argument("group", help="Ansible inventory group (e.g. ssl_cert)")
    stage_ssl_grp.add_argument("--vault-dir", **_vault_dir_arg)
    stage_ssl_grp.add_argument(
        "--hosts-ini", default="ansible/inventory/hosts.ini", metavar="FILE",
    )

    stage_pwds = vault_sub.add_parser(
        "stage-passwords",
        help="Write admin-passwords.yml from stick (admin only; delete after use)",
    )
    stage_pwds.add_argument(
        "--output", default="/tmp/lx-admin-passwords.yml", metavar="FILE",
        help="Output path (default: /tmp/lx-admin-passwords.yml)",
    )
    stage_pwds.add_argument(
        "--username", metavar="USERNAME", default=None,
        help="Limit to a single user",
    )

    stage_kc = vault_sub.add_parser(
        "stage-keycloak-admin",
        help="Stage the keycloak_admin password for a host (vault-encrypted, never in Nix store)",
    )
    stage_kc.add_argument("--hostname", required=True, help="Target hostname (e.g. h-01)")
    stage_kc.add_argument("--vault-dir", **_vault_dir_arg)

    vault_status = vault_sub.add_parser("status", help="Show staged secrets per hostname")
    vault_status.add_argument("hostname", nargs="?", default=None)
    vault_status.add_argument("--vault-dir", **_vault_dir_arg)

    return root


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

DISPATCH = {
    ("stick",    "check"):            cmd_stick_check,
    ("stick",    "init"):             cmd_stick_init,
    ("stick",    "backup"):           cmd_stick_backup,
    ("identity", "list"):             cmd_identity_list,
    ("identity", "gen-user"):         cmd_identity_gen_user,
    ("identity", "gen-host"):         cmd_identity_gen_host,
    ("identity", "import-keypair"):   cmd_identity_import_keypair,
    ("identity", "import-infra-key"): cmd_identity_import_infra_key,
    ("identity", "sync-inventory"):   cmd_identity_sync_inventory,
    ("user",     "set-password"):     cmd_user_set_password,
    ("user",     "show-hash"):        cmd_user_show_hash,
    ("user",     "show-password"):    cmd_user_show_password,
    ("user",     "sync"):             cmd_user_sync,
    ("admin",    "import-snippet"):   cmd_admin_import_snippet,
    ("admin",    "import-pubkey"):    cmd_admin_import_pubkey,
    ("admin",    "list-users"):       cmd_admin_list_users,
    ("cert",     "list"):             cmd_cert_list,
    ("cert",     "import-ssl"):       cmd_cert_import_ssl,
    ("cert",     "import-openvpn"):   cmd_cert_import_openvpn,
    ("cert",     "deploy-ssl"):       cmd_cert_deploy_ssl,
    ("cert",     "deploy-openvpn"):   cmd_cert_deploy_openvpn,
    ("vault",    "stage-ssl"):              cmd_vault_stage_ssl,
    ("vault",    "stage-ssl-group"):        cmd_vault_stage_ssl_group,
    ("vault",    "stage-passwords"):        cmd_vault_stage_passwords,
    ("vault",    "stage-keycloak-admin"):   cmd_vault_stage_keycloak_admin,
    ("vault",    "status"):                 cmd_vault_status,
}


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    fn = DISPATCH.get((args.command, args.subcommand))
    if fn is None:
        parser.print_help()
        sys.exit(1)
    fn(args)


if __name__ == "__main__":
    main()
