"""Generate the repository documentation index from MkDocs navigation."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import tempfile
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = REPO_ROOT / "mkdocs.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "TABLE_OF_CONTENTS.md"


class MkDocsLoader(yaml.SafeLoader):
    """Load MkDocs YAML safely while preserving Python-name references."""


MkDocsLoader.add_multi_constructor(
    "tag:yaml.org,2002:python/name:",
    lambda _loader, suffix, _node: suffix,
)


def _load_navigation(config_path: Path) -> list[Any]:
    config = yaml.load(
        config_path.read_text(encoding="utf-8"), Loader=MkDocsLoader
    )
    navigation = config.get("nav") if isinstance(config, dict) else None
    if not isinstance(navigation, list):
        raise ValueError(f"MkDocs navigation is missing or invalid: {config_path}")
    return navigation


def _link(title: str, target: str) -> str:
    if target.startswith(("http://", "https://")):
        return f"[{title}]({target})"
    return f"[{title}](docs/{target.removeprefix('./')})"


def _render_items(items: list[Any], depth: int = 0) -> list[str]:
    lines: list[str] = []
    indent = "  " * depth
    for item in items:
        if isinstance(item, str):
            title = Path(item).stem.replace("-", " ").title()
            lines.append(f"{indent}- {_link(title, item)}")
            continue

        if not isinstance(item, dict) or len(item) != 1:
            raise ValueError(f"Unsupported MkDocs navigation entry: {item!r}")

        title, value = next(iter(item.items()))
        if isinstance(value, str):
            lines.append(f"{indent}- {_link(str(title), value)}")
        elif isinstance(value, list):
            lines.append(f"{indent}- **{title}**")
            lines.extend(_render_items(value, depth + 1))
        else:
            raise ValueError(f"Unsupported MkDocs navigation value: {value!r}")
    return lines


def render_toc(config_path: Path = DEFAULT_CONFIG) -> str:
    lines = [
        "# Table of Contents",
        "",
        "<!-- Generated from mkdocs.yaml. Do not edit this file directly. -->",
        "",
        *_render_items(_load_navigation(config_path)),
    ]
    return "\n".join(lines) + "\n"


def write_toc(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=output.parent, prefix=f".{output.name}.", suffix=".tmp"
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate TABLE_OF_CONTENTS.md from mkdocs.yaml navigation."
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the existing output does not match MkDocs navigation",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        expected = render_toc(args.config.resolve())
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    output = args.output.resolve()
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.is_file() else ""
        if actual != expected:
            print(
                f"error: {output} is stale; run: devenv tasks run docs:toc-generator",
                file=sys.stderr,
            )
            return 1
        print(f"Documentation index is current: {output}")
        return 0

    write_toc(output, expected)
    print(f"Generated documentation index: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
