---
- name: Apply the managed-host baseline
  hosts: managed
  become: true
  roles:
    - managed

- name: Configure the main PostgreSQL host
  hosts: s-02
  become: true
  roles:
    - postgres_host_main

- name: Deploy development access
  hosts: gs-01, gs-02, gc-05, s-04
  become: true
  roles:
    - dev_access

- name: Configure Nginx hosts
  gather_facts: false
  hosts: nginx_host
  become: true
  roles:
    - nginx_host

- name: Configure Keycloak hosts
  gather_facts: false
  hosts: keycloak_host
  become: true
  roles:
    - keycloak_host

- name: Configure Nextcloud hosts
  hosts: nextcloud_host
  gather_facts: false
  become: true
  roles:
    - nextcloud_host
