---
- name: Deploy ssl_cert from source
  ansible.builtin.copy:
    src: "{{ ssl_cert_ssl_cert_src }}"
    dest: "{{ ssl_cert_ssl_cert_dest }}"
    mode: "0660"
    owner: "{{ ansible_user }}"
    group: "sslCert"
  become: true
  no_log: true

- name: Deploy ssl_key from source
  ansible.builtin.copy:
    src: "{{ ssl_cert_ssl_key_src }}"
    dest: "{{ ssl_cert_ssl_key_dest }}"
    mode: "0660"
    owner: "{{ ansible_user }}"
    group: "sslCert"
  become: true
  no_log: true
