{
  # Generated by luxnix-render-boot-decryption-config; do not edit directly.
  boot.initrd.availableKernelModules = [
    "dm-crypt"
    "sd_mod"
    "usb_storage"
  ];

  boot.initrd.luks.devices = {
    "cryptroot" = {
      keyFile = "/dev/disk/by-uuid/00acbcc0-b74f-4442-9460-b2e2d4e5042d";
      keyFileOffset = 52428800;
      keyFileSize = 4096;
      preLVM = true;
      keyFileTimeout = 10; # If no prompt is displayed, try pressing Esc.
    };
  };
}
